"""Geography (GS). Stages: PRE/MAINS; MH = Maharashtra weightage."""


def _t(tid, text, stages=("PRE", "MAINS"), mh=False):
    d = {"id": tid, "text": text, "stages": list(stages)}
    if mh:
        d["mh"] = True
    return d


SUBJECT = {
    "key": "geography",
    "title": "Geography",
    "icon": "G",
    "blurb": "Physical, Indian, World & Maharashtra geography, human/economic geography, geophysical phenomena. Prelims + Mains GS-1.",
    "category": "General Studies",
    "sections": [
        {"name": "Geomorphology", "groups": [
            {"name": "Earth's Interior & Crust", "topics": [
                _t("geo-gm-origin", "Origin and evolution of the earth"),
                _t("geo-gm-interior", "Interior of the earth — layers and discontinuities"),
                _t("geo-gm-rocks", "Rocks — igneous, sedimentary, metamorphic; rock cycle"),
                _t("geo-gm-minerals", "Minerals and their properties"),
                _t("geo-gm-isostasy", "Isostasy and earth movements"),
                _t("geo-gm-geologictime", "Geological time scale"),
            ]},
            {"name": "Tectonics & Landforms", "topics": [
                _t("geo-gm-continental", "Continental drift and plate tectonics"),
                _t("geo-gm-mountains", "Mountain building — fold and block mountains"),
                _t("geo-gm-volcano", "Volcanoes — types and distribution"),
                _t("geo-gm-earthquake", "Earthquakes — causes, seismic zones"),
                _t("geo-gm-fluvial", "Fluvial landforms — erosion and deposition"),
                _t("geo-gm-glacial", "Glacial, aeolian, coastal and karst landforms"),
                _t("geo-gm-weathering", "Weathering, mass movement and soil formation"),
            ]},
        ]},
        {"name": "Climatology", "groups": [
            {"name": "Atmosphere", "topics": [
                _t("geo-cl-composition", "Composition and structure of atmosphere"),
                _t("geo-cl-insolation", "Insolation and heat budget"),
                _t("geo-cl-temperature", "Temperature distribution and inversion"),
                _t("geo-cl-pressure", "Pressure belts and planetary winds"),
                _t("geo-cl-humidity", "Humidity, condensation, precipitation types"),
                _t("geo-cl-clouds", "Clouds and forms of precipitation"),
            ]},
            {"name": "Weather Systems & Climate", "topics": [
                _t("geo-cl-airmass", "Air masses and fronts"),
                _t("geo-cl-cyclone", "Tropical and temperate cyclones"),
                _t("geo-cl-jetstream", "Jet streams"),
                _t("geo-cl-elnino", "El Nino, La Nina and ENSO"),
                _t("geo-cl-iod", "Indian Ocean Dipole and Walker circulation"),
                _t("geo-cl-monsoon", "Indian monsoon — mechanism and variability"),
                _t("geo-cl-classification", "Koppen's climate classification"),
                _t("geo-cl-climatechange", "Climate change — global warming evidence"),
                _t("geo-cl-localwinds", "Local and seasonal winds"),
            ]},
        ]},
        {"name": "Oceanography", "groups": [
            {"name": "Oceans", "topics": [
                _t("geo-oc-relief", "Ocean bottom relief"),
                _t("geo-oc-temperature", "Temperature and salinity distribution"),
                _t("geo-oc-currents", "Ocean currents — causes and effects"),
                _t("geo-oc-tides", "Tides and waves"),
                _t("geo-oc-coral", "Coral reefs and marine ecosystems"),
                _t("geo-oc-resources", "Marine resources"),
                _t("geo-oc-deposits", "Ocean deposits and continental margins"),
                _t("geo-oc-elnino-ocean", "Ocean-atmosphere interactions"),
            ]},
        ]},
        {"name": "Physical Geography of India", "groups": [
            {"name": "Physiography", "topics": [
                _t("geo-in-himalayas", "The Himalayas — divisions (Trans, Greater, Lesser, Shiwalik)"),
                _t("geo-in-himalayas-regional", "Regional Himalayas — Punjab, Kumaon, Nepal, Assam"),
                _t("geo-in-plains", "Northern plains — divisions"),
                _t("geo-in-plateau", "Peninsular plateau and Deccan trap"),
                _t("geo-in-ghats", "Western and Eastern Ghats"),
                _t("geo-in-coastal", "Coastal plains"),
                _t("geo-in-islands", "Islands — Andaman-Nicobar, Lakshadweep"),
                _t("geo-in-deserts", "Indian (Thar) desert"),
            ]},
            {"name": "Himalayan Drainage", "topics": [
                _t("geo-riv-indus", "Indus system — tributaries (Jhelum, Chenab, Ravi, Beas, Sutlej)"),
                _t("geo-riv-ganga", "Ganga system and tributaries (Yamuna, Ghaghara, Gandak, Kosi)"),
                _t("geo-riv-yamuna", "Yamuna and Chambal sub-systems"),
                _t("geo-riv-brahmaputra", "Brahmaputra system"),
            ]},
            {"name": "Peninsular Drainage", "topics": [
                _t("geo-riv-godavari", "Godavari"),
                _t("geo-riv-krishna", "Krishna"),
                _t("geo-riv-kaveri", "Kaveri"),
                _t("geo-riv-mahanadi", "Mahanadi"),
                _t("geo-riv-narmada", "Narmada"),
                _t("geo-riv-tapi", "Tapi"),
                _t("geo-in-lakes", "Lakes, waterfalls and wetlands"),
                _t("geo-in-watershed", "Drainage patterns and watershed management"),
                _t("geo-in-interlinking", "River interlinking and water disputes", ("MAINS",)),
            ]},
            {"name": "Soils of India", "topics": [
                _t("geo-soil-alluvial", "Alluvial soil"),
                _t("geo-soil-black", "Black (regur) soil"),
                _t("geo-soil-red", "Red and yellow soil"),
                _t("geo-soil-laterite", "Laterite soil"),
                _t("geo-soil-arid", "Arid, saline and peaty soils"),
                _t("geo-soil-erosion", "Soil erosion and conservation"),
            ]},
            {"name": "Vegetation & Wildlife", "topics": [
                _t("geo-veg-tropical", "Tropical evergreen and deciduous forests"),
                _t("geo-veg-thorn", "Thorn, montane and mangrove forests"),
                _t("geo-veg-conservation", "Forest conservation and afforestation", ("MAINS",)),
                _t("geo-in-wildlife", "Wildlife sanctuaries and biosphere reserves"),
            ]},
            {"name": "Climate of India", "topics": [
                _t("geo-in-climate", "Climatic controls and factors"),
                _t("geo-in-seasons", "Indian seasons and weather phenomena"),
                _t("geo-in-rainfall", "Rainfall distribution and variability"),
            ]},
        ]},
        {"name": "Maharashtra Geography", "groups": [
            {"name": "Maharashtra Physical", "topics": [
                _t("geo-mh-physio", "Physiographic divisions — Konkan, Ghats, Plateau", ("PRE", "MAINS"), True),
                _t("geo-mh-ghats", "Western Ghats (Sahyadri) — significance", ("PRE", "MAINS"), True),
                _t("geo-mh-rivers", "Rivers of Maharashtra — Godavari, Krishna, Tapi", ("PRE", "MAINS"), True),
                _t("geo-mh-climate", "Climate and rainfall pattern", ("PRE", "MAINS"), True),
                _t("geo-mh-soils", "Soils of Maharashtra", ("PRE", "MAINS"), True),
                _t("geo-mh-forests", "Forests and biodiversity of Maharashtra", ("PRE", "MAINS"), True),
                _t("geo-mh-passes", "Ghats, passes and plateaus of Maharashtra", ("PRE", "MAINS"), True),
                _t("geo-mh-lakes", "Lakes, dams and major reservoirs", ("PRE", "MAINS"), True),
            ]},
            {"name": "Maharashtra Economic Geography", "topics": [
                _t("geo-mh-agri", "Agriculture and cropping pattern", ("PRE", "MAINS"), True),
                _t("geo-mh-cashcrops", "Cash crops — cotton, sugarcane, oilseeds", ("PRE", "MAINS"), True),
                _t("geo-mh-irrigation", "Irrigation and water resources", ("PRE", "MAINS"), True),
                _t("geo-mh-minerals", "Minerals and energy resources", ("PRE", "MAINS"), True),
                _t("geo-mh-industry", "Industrial regions of Maharashtra", ("PRE", "MAINS"), True),
                _t("geo-mh-transport", "Transport network and ports", ("PRE", "MAINS"), True),
                _t("geo-mh-urban", "Urbanization and major cities", ("PRE", "MAINS"), True),
                _t("geo-mh-divisions", "Administrative & revenue divisions, districts", ("PRE", "MAINS"), True),
                _t("geo-mh-drought", "Drought-prone regions and watershed (Jalyukt Shivar)", ("PRE", "MAINS"), True),
                _t("geo-mh-tourism", "Tourism geography of Maharashtra", ("PRE", "MAINS"), True),
            ]},
        ]},
        {"name": "Indian Economic Geography", "groups": [
            {"name": "Agriculture & Crops", "topics": [
                _t("geo-eco-agriculture", "Cropping seasons (Kharif, Rabi, Zaid)"),
                _t("geo-eco-foodcrops", "Food crops — rice, wheat, millets, pulses"),
                _t("geo-eco-cashcrops", "Cash crops — cotton, sugarcane, oilseeds, jute"),
                _t("geo-eco-plantation", "Plantation crops — tea, coffee, rubber, spices"),
                _t("geo-eco-irrigation", "Irrigation — types and major projects"),
            ]},
            {"name": "Minerals & Energy", "topics": [
                _t("geo-eco-metallic", "Metallic minerals — iron, manganese, bauxite, copper"),
                _t("geo-eco-nonmetallic", "Non-metallic minerals and distribution"),
                _t("geo-eco-coal", "Coal and petroleum reserves"),
                _t("geo-eco-renewable", "Renewable energy — solar, wind, hydro, nuclear"),
            ]},
            {"name": "Industry, Transport & Trade", "topics": [
                _t("geo-eco-industries", "Major industries — iron-steel, textiles, cement, IT"),
                _t("geo-eco-industrial-regions", "Industrial regions of India"),
                _t("geo-eco-transport", "Transport — road, rail, water, air"),
                _t("geo-eco-ports", "Major ports and inland waterways"),
                _t("geo-eco-trade", "Trade and economic corridors"),
            ]},
        ]},
        {"name": "Human & Settlement Geography", "groups": [
            {"name": "Population & Settlement", "topics": [
                _t("geo-hum-population", "Population distribution and density"),
                _t("geo-hum-growth", "Population growth and demographic transition"),
                _t("geo-hum-composition", "Population composition — age, sex, literacy"),
                _t("geo-hum-migration", "Migration — types, causes, effects"),
                _t("geo-hum-rural", "Rural settlements — types and patterns"),
                _t("geo-hum-urban", "Urban settlements and urbanization"),
                _t("geo-hum-urbanproblems", "Urban morphology and problems", ("MAINS",)),
                _t("geo-hum-tribes", "Tribes and human races"),
            ]},
            {"name": "Models & Theories", "topics": [
                _t("geo-hum-malthus", "Theories of population (Malthus, demographic transition)", ("MAINS",)),
                _t("geo-hum-central-place", "Central place theory (Christaller)", ("MAINS",)),
                _t("geo-hum-vonthunen", "Von Thunen and Weber location models", ("MAINS",)),
            ]},
        ]},
        {"name": "World Geography", "groups": [
            {"name": "Continents", "topics": [
                _t("geo-world-asia", "Asia — physical features and regions"),
                _t("geo-world-africa", "Africa — physical features and regions"),
                _t("geo-world-europe", "Europe — physical features and regions"),
                _t("geo-world-northamerica", "North America"),
                _t("geo-world-southamerica", "South America"),
                _t("geo-world-australia", "Australia and Oceania"),
                _t("geo-world-antarctica", "Antarctica"),
            ]},
            {"name": "Regions & Resources", "topics": [
                _t("geo-world-realms", "Major natural realms and biomes"),
                _t("geo-world-climate", "World climatic regions"),
                _t("geo-world-resources", "Distribution of natural resources"),
                _t("geo-world-agri", "World agricultural regions"),
                _t("geo-world-industry", "Industrial regions and location factors"),
                _t("geo-world-trade", "World trade and transport routes"),
            ]},
            {"name": "Map & Locations", "topics": [
                _t("geo-world-latlong", "Latitudes, longitudes, time zones"),
                _t("geo-world-motions", "Earth's motions, seasons, eclipses"),
                _t("geo-world-straits", "Important straits, canals and water bodies"),
                _t("geo-world-mountains", "Major mountain ranges and peaks of the world"),
                _t("geo-world-rivers", "Major rivers and river basins of the world"),
                _t("geo-world-deserts", "Major deserts and grasslands of the world"),
                _t("geo-world-volcanoes", "Major volcanoes and earthquake zones"),
            ]},
        ]},
        {"name": "Geophysical Phenomena & Hazards", "groups": [
            {"name": "Natural Hazards", "topics": [
                _t("geo-haz-earthquake", "Earthquakes — Indian seismic zones"),
                _t("geo-haz-tsunami", "Tsunamis"),
                _t("geo-haz-volcano", "Volcanic activity"),
                _t("geo-haz-cyclone", "Cyclones and storm surges"),
                _t("geo-haz-flood", "Floods"),
                _t("geo-haz-drought", "Droughts and desertification"),
                _t("geo-haz-landslide", "Landslides and avalanches"),
                _t("geo-haz-cloudburst", "Cloudbursts and flash floods"),
                _t("geo-haz-changes", "Changes in critical geographical features and ecosystems", ("MAINS",)),
            ]},
        ]},
        {"name": "Economic & Resource Geography (Concepts)", "groups": [
            {"name": "Agro-climatic & Planning Regions", "topics": [
                _t("geo-acz-india", "Agro-climatic zones of India"),
                _t("geo-acz-cropzones", "Crop-climate regions and farming systems"),
                _t("geo-acz-mh", "Agro-climatic zones of Maharashtra", ("PRE", "MAINS"), True),
                _t("geo-acz-droughtindia", "Drought and flood-prone regions of India"),
            ]},
            {"name": "Settlement & Cultural Geography", "topics": [
                _t("geo-cul-tribes", "Major tribes and their distribution"),
                _t("geo-cul-languages", "Linguistic regions of India"),
                _t("geo-cul-religion", "Religious composition and distribution"),
                _t("geo-cul-megacities", "Million-plus cities and metropolitan regions"),
            ]},
            {"name": "Location & Resources", "topics": [
                _t("geo-conc-primary", "Primary, secondary, tertiary, quaternary activities", ("MAINS",)),
                _t("geo-conc-factors", "Factors of industrial location", ("MAINS",)),
                _t("geo-conc-resource", "Resource classification and conservation", ("MAINS",)),
                _t("geo-conc-sustainable", "Sustainable development and carrying capacity", ("MAINS",)),
                _t("geo-conc-regional", "Regional planning and growth poles", ("MAINS",)),
                _t("geo-conc-remote", "Remote sensing, GIS and survey techniques"),
                _t("geo-conc-gps", "GPS and modern geographical tools"),
            ]},
        ]},
    ],
}
