# -*- coding: utf-8 -*-
"""Spring Integration, AMQP, Kafka, Pulsar."""

INTEGRATION = {
  "file":"spring-integration.html","title":"Spring Integration","logo":"I","cat":"Messaging",
  "subtitle":"Enterprise Integration Patterns (EIP) inside Spring — messaging, channels, endpoints.",
  "sections":[
    {"name":"1. Core Messaging","tag":"core","groups":[
      {"g":"Concepts","items":[
        "Enterprise Integration Patterns (EIP) overview",
        "Message (payload + headers)",
        "MessageHeaders & MessageHeaderAccessor",
        "Message channels concept",
        "Message endpoints concept",
        "Pipes-and-filters architecture",
        "Programming models (XML, annotations, Java DSL)",
      ]},
      {"g":"Message Channels","items":[
        "DirectChannel",
        "PublishSubscribeChannel",
        "QueueChannel",
        "PriorityChannel",
        "RendezvousChannel",
        "ExecutorChannel",
        "FluxMessageChannel (reactive)",
        "Channel interceptors (ChannelInterceptor)",
        "MessagingTemplate",
        "Scoped channels",
        "Channel adapter vs channel",
      ]},
      {"g":"Endpoints","items":[
        "Message endpoints overview",
        "ServiceActivator",
        "Transformer",
        "Filter",
        "Router (payload/header/recipient-list/exception-type)",
        "Splitter",
        "Aggregator",
        "Resequencer",
        "Header enricher / Content enricher",
        "Delayer",
        "Bridge",
        "Claim check (in/out)",
        "Chain (message handler chain)",
        "Gateway (messaging gateway, @MessagingGateway)",
        "Inbound/outbound channel adapters",
        "Inbound/outbound gateways",
        "Polling consumer & PollerMetadata",
        "Event-driven consumer",
      ]},
    ]},
    {"name":"2. Java DSL & Configuration","tag":"dsl","groups":[
      {"g":"DSL","items":[
        "IntegrationFlow & IntegrationFlows / Java DSL",
        "Lambdas in the DSL",
        "Sub-flows & nested flows",
        "Function & message processors in DSL",
        "@EnableIntegration",
        "@IntegrationComponentScan",
        "@MessageEndpoint & @ServiceActivator annotations",
        "Error handling (errorChannel, ErrorMessage)",
        "Global wiretap & message history",
        "Message store (in-memory, JDBC, MongoDB, Redis)",
        "Metadata store / idempotent receiver",
        "Distributed locks (LockRegistry)",
        "Control bus",
      ]},
    ]},
    {"name":"3. Channel Adapters (endpoints)","tag":"adapters","groups":[
      {"g":"Endpoint Modules","items":[
        "File support (read/write/tail)",
        "FTP / FTPS adapters",
        "SFTP adapters",
        "TCP & UDP support",
        "HTTP support (inbound/outbound)",
        "WebFlux support",
        "Web Services (WS) support",
        "JMS support",
        "AMQP support",
        "Apache Kafka support",
        "MQTT support",
        "STOMP support",
        "WebSocket support",
        "Mail (IMAP/POP3/SMTP) support",
        "JDBC & stored procedure adapters",
        "JPA support",
        "MongoDB / Redis / Cassandra adapters",
        "JMX support",
        "RMI (legacy)",
        "Resource inbound adapter",
        "Feed (RSS/Atom) adapter",
        "XMPP support",
        "Zookeeper support",
        "Syslog support",
        "Hazelcast support",
        "R2DBC support",
        "GraphQL support",
        "SMB support",
      ]},
    ]},
    {"name":"4. Advanced & System","tag":"adv","groups":[
      {"g":"System Management","items":[
        "Message transformation (object<->JSON/XML, Avro)",
        "Codec (Kryo)",
        "XML support (XPath, XSLT, marshalling)",
        "Scripting support (Groovy, JSR-223)",
        "Groovy DSL",
        "Transaction support in flows",
        "Reactive Streams support",
        "Error handling strategies & retry advice",
        "RequestHandlerRetryAdvice / CircuitBreaker advice",
        "Rate limiter advice",
        "Smart polling",
        "Message history & wire tap",
        "JMX & management endpoints",
        "Integration graph (IntegrationGraphServer)",
        "Testing support (MockIntegration, @SpringIntegrationTest)",
      ]},
    ]},
  ],
}

AMQP = {
  "file":"spring-amqp.html","title":"Spring AMQP","logo":"Aq","cat":"Messaging",
  "subtitle":"Spring abstractions for AMQP messaging — Spring Rabbit & RabbitMQ.",
  "sections":[
    {"name":"1. AMQP Fundamentals","tag":"core","groups":[
      {"g":"Concepts","items":[
        "AMQP protocol overview (exchanges, queues, bindings, routing keys)",
        "Exchange types (direct, topic, fanout, headers)",
        "Spring AMQP project structure (spring-amqp, spring-rabbit)",
        "Message abstraction (Message, MessageProperties)",
        "ConnectionFactory (CachingConnectionFactory)",
        "Connection & channel caching modes",
        "AmqpTemplate / RabbitTemplate",
        "AmqpAdmin / RabbitAdmin (declaring resources)",
        "Queue, Exchange, Binding builder API",
        "Declarable beans & auto-declaration",
      ]},
    ]},
    {"name":"2. Sending & Receiving","tag":"messaging","groups":[
      {"g":"Producing","items":[
        "Sending messages (convertAndSend)",
        "MessageConverter (SimpleMessageConverter, Jackson2JsonMessageConverter)",
        "MessagePostProcessor",
        "Publisher confirms & returns",
        "Correlation data",
        "RabbitTemplate retry & recovery",
        "Mandatory messages & returns callback",
        "Batching (BatchingRabbitTemplate)",
        "RPC pattern (sendAndReceive)",
        "Direct reply-to",
      ]},
      {"g":"Consuming","items":[
        "Message listener containers (Simple vs Direct)",
        "@RabbitListener",
        "@RabbitHandler (multi-method)",
        "@EnableRabbit & RabbitListenerContainerFactory",
        "Listener concurrency & prefetch",
        "Acknowledge modes (auto/manual/none)",
        "Message conversion in listeners",
        "@Payload / @Header / @Headers in listeners",
        "Reply via @SendTo",
        "Container error handling & retries",
        "Dead letter exchanges / queues (DLX/DLQ)",
        "Conditional rejection & requeue",
        "Listener container lifecycle",
        "Consumer batch mode",
      ]},
    ]},
    {"name":"3. Advanced","tag":"adv","groups":[
      {"g":"Advanced Features","items":[
        "Transactions & transactional channels",
        "Message grouping / stream support (RabbitMQ Streams plugin)",
        "Spring AMQP & RabbitMQ Super Streams (partitioned)",
        "Delayed message exchange",
        "Federation & shovel (broker concepts)",
        "Multi-rabbit (multiple brokers)",
        "Connection name & blocked connection handling",
        "Micrometer metrics & observation",
        "Testing support (@RabbitListenerTest, RabbitListenerTestHarness)",
        "Mock/embedded broker for tests (Testcontainers)",
        "Error handling exception hierarchy",
        "Message TTL & queue length limits",
        "Priority queues",
        "Quorum & lazy queues",
      ]},
    ]},
  ],
}

KAFKA = {
  "file":"spring-for-apache-kafka.html","title":"Spring for Apache Kafka","logo":"K","cat":"Messaging",
  "subtitle":"Spring concepts applied to Kafka — KafkaTemplate, listeners, streams.",
  "sections":[
    {"name":"1. Core (Producer/Consumer)","tag":"core","groups":[
      {"g":"Producing","items":[
        "Kafka fundamentals (topics, partitions, offsets, brokers)",
        "ProducerFactory & DefaultKafkaProducerFactory",
        "KafkaTemplate",
        "Sending (send, with key/partition/timestamp)",
        "ListenableFuture / CompletableFuture results",
        "Transactions & transactional producer",
        "RoutingKafkaTemplate",
        "ReplyingKafkaTemplate (request/reply)",
        "Producer interceptors",
        "Message keys & partitioning",
      ]},
      {"g":"Consuming","items":[
        "ConsumerFactory & DefaultKafkaConsumerFactory",
        "@KafkaListener",
        "@EnableKafka & KafkaListenerContainerFactory",
        "Message listener containers (KafkaMessageListenerContainer / Concurrent)",
        "Listener concurrency & partitions",
        "Acknowledgment modes (AckMode)",
        "Manual acknowledgment (Acknowledgment)",
        "Batch listeners",
        "@Payload / @Header (KafkaHeaders)",
        "Consumer-aware listeners",
        "Rebalance listeners",
        "Seeking to offsets (ConsumerSeekAware)",
        "Pausing & resuming containers",
        "Committing offsets",
      ]},
    ]},
    {"name":"2. Serialization & Error Handling","tag":"serde","groups":[
      {"g":"Serialization","items":[
        "Serializers / Deserializers (String, JSON, Avro, etc.)",
        "JsonSerializer / JsonDeserializer & type mapping",
        "ErrorHandlingDeserializer",
        "Delegating & retrying deserializers",
        "Spring Messaging converters",
        "Schema Registry (Avro/Confluent)",
      ]},
      {"g":"Error Handling & Retry","items":[
        "CommonErrorHandler",
        "DefaultErrorHandler & back-off",
        "Dead-letter publishing (DeadLetterPublishingRecoverer)",
        "Non-blocking retries (@RetryableTopic)",
        "Retry topics & DLT topics",
        "Recovery callbacks",
        "Container stopping error handler",
        "After-rollback processor (transactions)",
      ]},
    ]},
    {"name":"3. Streams & Advanced","tag":"adv","groups":[
      {"g":"Kafka Streams","items":[
        "Spring Kafka Streams support",
        "StreamsBuilderFactoryBean",
        "@EnableKafkaStreams",
        "KStream / KTable usage",
        "Streams configuration & topology",
        "Interactive queries",
        "Streams error handling",
      ]},
      {"g":"Advanced & Tooling","items":[
        "Kafka transactions & exactly-once semantics",
        "Transaction synchronization with DB",
        "KafkaAdmin & topic provisioning (NewTopic beans)",
        "Micrometer metrics & observation / tracing",
        "Request/reply over Kafka",
        "Delegating listeners by type",
        "Listener container properties (poll timeout, idle events)",
        "Container groups & registry",
        "Multi-method listeners (@KafkaHandler)",
        "Testing (EmbeddedKafka / @EmbeddedKafka)",
        "Testcontainers for Kafka",
        "JUnit support (KafkaTestUtils)",
      ]},
    ]},
  ],
}

PULSAR = {
  "file":"spring-for-apache-pulsar.html","title":"Spring for Apache Pulsar","logo":"P","cat":"Messaging",
  "subtitle":"Spring-friendly building blocks for Apache Pulsar messaging.",
  "sections":[
    {"name":"1. Core Pulsar Support","tag":"core","groups":[
      {"g":"Producing & Consuming","items":[
        "Apache Pulsar concepts (topics, subscriptions, tenants, namespaces)",
        "PulsarClient configuration",
        "PulsarTemplate",
        "Sending messages (send / sendAsync)",
        "Message routing & partitioning",
        "@PulsarListener",
        "@EnablePulsar",
        "Subscription types (exclusive, shared, failover, key_shared)",
        "Acknowledgment modes",
        "Batch listeners",
        "PulsarConsumerFactory / PulsarProducerFactory",
        "PulsarReader & @PulsarReader",
      ]},
      {"g":"Schema & Serialization","items":[
        "Pulsar schema support (primitive, JSON, Avro, Protobuf, KeyValue)",
        "Custom schema resolution",
        "Schema auto-detection",
        "Message key/value schemas",
      ]},
    ]},
    {"name":"2. Advanced","tag":"adv","groups":[
      {"g":"Advanced Features","items":[
        "Dead letter topics & redelivery",
        "Negative acknowledgment & retry",
        "Message TTL & delayed delivery",
        "Pulsar transactions",
        "Reactive Pulsar support (ReactivePulsarTemplate / @ReactivePulsarListener)",
        "Pulsar admin & auto topic creation",
        "Error handling",
        "Observability (Micrometer)",
        "Spring Boot auto-configuration",
        "Pulsar Functions (concepts)",
        "Testing support",
      ]},
    ]},
  ],
}

PROJECTS = [INTEGRATION, AMQP, KAFKA, PULSAR]
