# -*- coding: utf-8 -*-
"""Spring Framework + Spring Boot — exhaustive micro-topics."""

FRAMEWORK = {
  "file":"spring-framework.html","title":"Spring Framework","logo":"F","cat":"Core",
  "subtitle":"The foundation: IoC container, AOP, data access, MVC, WebFlux, testing.",
  "sections":[
    {"name":"1. Introduction & Setup","tag":"intro","groups":[
      {"g":"What Spring Is","items":[
        "What the Spring Framework is & its goals",
        "History & evolution (Spring 1 → 6)",
        "Spring Framework vs Spring Boot vs Spring ecosystem",
        "Spring modules overview (spring-core, -context, -beans, -aop, -web, etc.)",
        "Jakarta EE baseline (jakarta.* namespace migration from javax.*)",
        "JDK 17+ baseline (Spring 6)",
        "Spring 6 / Spring Boot 3 generation overview",
        "Licensing (Apache License 2.0)",
        "Release versions & support timelines",
      ]},
      {"g":"Getting Started","items":[
        "Adding Spring with Maven",
        "Adding Spring with Gradle",
        "Spring BOM (Bill of Materials) for dependency management",
        "spring-context as the typical starting dependency",
        "Logging dependencies (spring-jcl / commons-logging bridge)",
        "Choosing module dependencies",
      ]},
    ]},
    {"name":"2. IoC Container & Beans","tag":"core","groups":[
      {"g":"Container Fundamentals","items":[
        "Inversion of Control (IoC) principle",
        "Dependency Injection (DI) concept",
        "BeanFactory interface",
        "ApplicationContext interface",
        "BeanFactory vs ApplicationContext",
        "Configuration metadata (XML, annotations, Java)",
        "ClassPathXmlApplicationContext",
        "FileSystemXmlApplicationContext",
        "AnnotationConfigApplicationContext",
        "GenericApplicationContext",
        "Instantiating a container",
        "Container startup & refresh()",
        "Graceful shutdown & close()",
      ]},
      {"g":"Bean Definition","items":[
        "What a Spring bean is",
        "Bean definition & BeanDefinition object",
        "Naming beans",
        "Bean aliases",
        "Instantiation with a constructor",
        "Instantiation with a static factory method",
        "Instantiation with an instance factory method",
        "FactoryBean interface",
        "Determining a bean's runtime type",
      ]},
      {"g":"Dependency Injection","items":[
        "Constructor-based dependency injection",
        "Constructor argument resolution",
        "Constructor argument type matching",
        "Constructor argument index / name",
        "Setter-based dependency injection",
        "Constructor vs setter injection trade-offs",
        "Field injection (and why it is discouraged)",
        "Method injection",
        "Lookup method injection (@Lookup)",
        "Arbitrary method replacement",
        "Dependency resolution process",
        "Circular dependencies & how to resolve them",
        "Lazy-initialized beans (@Lazy / lazy-init)",
      ]},
      {"g":"Configuring Beans (collaborators)","items":[
        "Straight values (primitives, Strings)",
        "References to other beans (ref)",
        "Inner beans",
        "Collections (List, Set, Map, Props)",
        "Collection merging",
        "Null and empty string values",
        "Compound property names",
        "depends-on / @DependsOn",
        "p-namespace (XML)",
        "c-namespace (XML)",
      ]},
      {"g":"Bean Scopes","items":[
        "singleton scope (default)",
        "prototype scope",
        "request scope",
        "session scope",
        "application scope",
        "websocket scope",
        "Scoped beans as dependencies (scoped proxies)",
        "Custom scope (Scope interface) & registration",
        "Thread scope (SimpleThreadScope)",
      ]},
      {"g":"Bean Lifecycle","items":[
        "Lifecycle callbacks overview",
        "InitializingBean / afterPropertiesSet()",
        "DisposableBean / destroy()",
        "@PostConstruct annotation",
        "@PreDestroy annotation",
        "init-method / destroy-method attributes",
        "default-init-method / default-destroy-method",
        "Lifecycle & SmartLifecycle interfaces",
        "Phased startup/shutdown (Phased)",
        "Startup shutdown order",
        "Lifecycle mechanism combination order",
        "Aware interfaces overview",
        "BeanNameAware",
        "BeanFactoryAware",
        "ApplicationContextAware",
        "Other *Aware interfaces (ResourceLoaderAware, EnvironmentAware, etc.)",
      ]},
      {"g":"Container Extension Points","items":[
        "BeanPostProcessor interface",
        "Multiple BeanPostProcessors & ordering",
        "BeanFactoryPostProcessor interface",
        "PropertySourcesPlaceholderConfigurer",
        "PropertyOverrideConfigurer",
        "Customizing instantiation logic with FactoryBean",
      ]},
      {"g":"Annotation-Based Configuration","items":[
        "@Required (deprecated)",
        "@Autowired (constructor, setter, field, method, arrays/collections)",
        "@Autowired required attribute",
        "Optional/ObjectProvider/Optional<> injection",
        "Fine-tuning with @Primary",
        "@Fallback beans",
        "Qualifiers with @Qualifier",
        "Custom qualifier annotations",
        "@Resource (JSR-250) injection",
        "@Value injection & SpEL",
        "@PostConstruct / @PreDestroy (JSR-250)",
        "Generics as autowiring qualifiers",
        "CustomAutowireConfigurer",
      ]},
      {"g":"Classpath Scanning & Stereotypes","items":[
        "@Component stereotype",
        "@Repository, @Service, @Controller stereotypes",
        "Meta-annotations & composed annotations",
        "@ComponentScan & component scanning",
        "Include/exclude filters (type, annotation, assignable, aspectj, regex, custom)",
        "Auto-detecting components",
        "Naming autodetected components (BeanNameGenerator)",
        "Providing a scope (@Scope, ScopeMetadataResolver)",
        "@Indexed & candidate component index",
      ]},
      {"g":"Java-based Configuration","items":[
        "@Configuration classes",
        "@Bean methods",
        "Bean naming/aliasing in @Bean",
        "Bean description (@Description)",
        "Injecting inter-bean dependencies",
        "Lite @Bean mode (in @Component) vs full @Configuration (CGLIB proxy)",
        "proxyBeanMethods attribute",
        "@Import to compose configurations",
        "Conditional import with @Conditional",
        "ImportSelector / DeferredImportSelector",
        "ImportBeanDefinitionRegistrar",
        "@ImportResource (mixing XML)",
        "@PropertySource",
        "Combining Java & XML configuration",
        "Bean method lifecycle callbacks (initMethod/destroyMethod)",
      ]},
      {"g":"Environment Abstraction","items":[
        "Environment interface",
        "Bean definition profiles (@Profile)",
        "Activating a profile (spring.profiles.active)",
        "Default profile",
        "PropertySource abstraction",
        "Property resolution order & precedence",
        "@PropertySource with placeholders",
        "Placeholder resolution in statements",
        "MutablePropertySources / ConfigurableEnvironment",
      ]},
    ]},
    {"name":"3. Resources, Validation, SpEL, AOT","tag":"core","groups":[
      {"g":"Resources","items":[
        "Resource interface",
        "UrlResource, ClassPathResource, FileSystemResource",
        "ServletContextResource, InputStreamResource, ByteArrayResource",
        "ResourceLoader & ResourceLoaderAware",
        "ResourcePatternResolver (classpath*:)",
        "Resource as dependency",
        "Application contexts & resource paths",
      ]},
      {"g":"Validation, Binding, Conversion","items":[
        "Validator interface",
        "Errors & error codes (MessageCodesResolver)",
        "DataBinder",
        "BeanWrapper & property access",
        "PropertyEditors (built-in & custom)",
        "Spring type conversion (ConversionService)",
        "Converter SPI / Converter / ConverterFactory / GenericConverter",
        "Formatter SPI & FormatterRegistry",
        "Field formatting (@NumberFormat, @DateTimeFormat)",
        "Bean Validation (Jakarta Validation / JSR-380)",
        "@Valid / @Validated & method validation",
        "Configuring a LocalValidatorFactoryBean",
        "Spring MVC validation integration",
      ]},
      {"g":"Spring Expression Language (SpEL)","items":[
        "SpEL overview & ExpressionParser",
        "EvaluationContext (StandardEvaluationContext / SimpleEvaluationContext)",
        "Literal expressions",
        "Properties, arrays, lists, maps, indexers",
        "Inline lists & maps",
        "Array construction",
        "Methods & operators (relational, logical, mathematical, string)",
        "Assignment",
        "Types (T operator)",
        "Constructors",
        "Variables (#this, #root)",
        "Functions",
        "Bean references (@beanName)",
        "Ternary, Elvis, and safe-navigation operators",
        "Collection selection & projection",
        "Templated expressions",
        "SpEL compilation",
      ]},
      {"g":"Ahead-of-Time (AOT)","items":[
        "AOT processing overview",
        "AOT vs JIT",
        "GraalVM native image support",
        "Runtime hints (reflection, resources, serialization, proxies)",
        "RuntimeHintsRegistrar",
        "@ImportRuntimeHints / @RegisterReflectionForBinding",
        "AOT-processed bean definitions",
        "Best practices & limitations of AOT",
      ]},
      {"g":"Application Events","items":[
        "ApplicationEvent & ApplicationListener",
        "Standard context events (Refreshed, Started, Stopped, Closed)",
        "Annotation-based event listeners (@EventListener)",
        "Asynchronous listeners (@Async)",
        "Ordering listeners (@Order)",
        "Generic events (ResolvableType)",
        "Transaction-bound events (@TransactionalEventListener)",
        "Publishing events (ApplicationEventPublisher)",
      ]},
      {"g":"Misc Core","items":[
        "Internationalization (MessageSource)",
        "ResourceBundleMessageSource / ReloadableResourceBundleMessageSource",
        "Standard & custom events recap",
        "Convenient ApplicationContext instantiation for web apps",
        "Registering a LoadTimeWeaver",
        "JavaBeans PropertyEditor registration (CustomEditorConfigurer)",
        "Task execution & scheduling abstraction (TaskExecutor/TaskScheduler)",
        "@Scheduled & @EnableScheduling",
        "Cron expressions",
        "@Async & @EnableAsync",
        "AsyncUncaughtExceptionHandler",
        "Null-safety annotations (@Nullable, @NonNull)",
        "Data buffers & codecs",
        "Spring JCL logging bridge",
        "AppCDS (Application Class Data Sharing)",
      ]},
    ]},
    {"name":"4. Aspect-Oriented Programming (AOP)","tag":"aop","groups":[
      {"g":"AOP Concepts","items":[
        "Why AOP — cross-cutting concerns",
        "Aspect, Join point, Advice, Pointcut",
        "Introduction, Target object, AOP proxy, Weaving",
        "Spring AOP capabilities & goals",
        "AOP proxies (JDK dynamic vs CGLIB)",
      ]},
      {"g":"@AspectJ Support","items":[
        "Enabling @AspectJ support (@EnableAspectJAutoProxy)",
        "Declaring an aspect (@Aspect)",
        "Declaring a pointcut",
        "Supported pointcut designators (execution, within, this, target, args, @annotation, etc.)",
        "Combining pointcut expressions",
        "Sharing named pointcut definitions",
        "@Before advice",
        "@AfterReturning advice",
        "@AfterThrowing advice",
        "@After (finally) advice",
        "@Around advice & ProceedingJoinPoint",
        "Advice parameters & passing parameters",
        "Generics with advice parameters",
        "Advice ordering (@Order)",
        "Introductions (@DeclareParents)",
        "Aspect instantiation models (perthis, pertarget)",
      ]},
      {"g":"Schema & Proxying","items":[
        "Schema-based AOP support (<aop:config>)",
        "Declaring advice/pointcut via XML",
        "Advisors",
        "Choosing AOP declaration style",
        "Programmatic proxies (ProxyFactory)",
        "Proxying mechanisms (JDK vs CGLIB) & forcing CGLIB",
        "Understanding AOP proxies & self-invocation pitfalls",
        "Using AspectJ with Spring (LTW — load-time weaving)",
        "Configuring AspectJ aspects with Spring IoC",
      ]},
    ]},
    {"name":"5. Data Access & Transactions","tag":"data","groups":[
      {"g":"Transaction Management","items":[
        "Spring transaction abstraction overview",
        "Global vs local transactions",
        "PlatformTransactionManager",
        "TransactionDefinition (propagation, isolation, timeout, read-only)",
        "TransactionStatus",
        "Declarative transaction management (@Transactional)",
        "@EnableTransactionManagement",
        "@Transactional settings & attributes",
        "Propagation behaviors (REQUIRED, REQUIRES_NEW, NESTED, SUPPORTS, etc.)",
        "Isolation levels",
        "Rollback rules (rollbackFor / noRollbackFor)",
        "Transaction proxy & self-invocation limitation",
        "Programmatic transaction management (TransactionTemplate)",
        "TransactionalOperator (reactive)",
        "Multiple transaction managers with @Transactional(\"name\")",
        "Transaction-bound events",
        "Application-managed vs container-managed transactions",
        "ReactiveTransactionManager",
      ]},
      {"g":"DAO Support","items":[
        "Consistent exception hierarchy (DataAccessException)",
        "@Repository & exception translation",
        "PersistenceExceptionTranslationPostProcessor",
      ]},
      {"g":"JDBC","items":[
        "Spring JDBC packages overview",
        "JdbcTemplate",
        "Querying & updating with JdbcTemplate",
        "NamedParameterJdbcTemplate",
        "SimpleJdbcInsert / SimpleJdbcCall",
        "RowMapper / ResultSetExtractor / RowCallbackHandler",
        "SQLExceptionTranslator",
        "Batch operations",
        "DataSource configuration & DataSourceUtils",
        "Embedded database support (H2, HSQL, Derby)",
        "Initializing a DataSource (schema/data scripts)",
        "Modeling JDBC operations as Java objects (MappingSqlQuery, SqlUpdate)",
        "Handling LOBs",
        "Stored procedures",
        "JdbcClient (fluent API)",
      ]},
      {"g":"R2DBC (Reactive)","items":[
        "R2DBC overview",
        "DatabaseClient",
        "ConnectionFactory configuration",
        "Reactive transactions with R2DBC",
      ]},
      {"g":"ORM / JPA / Hibernate","items":[
        "ORM integration overview & benefits",
        "General ORM considerations",
        "Hibernate integration (LocalSessionFactoryBean)",
        "JPA integration (LocalContainerEntityManagerFactoryBean)",
        "Persistence unit & EntityManagerFactory",
        "@PersistenceContext / @PersistenceUnit",
        "JpaTransactionManager",
        "JpaVendorAdapter (Hibernate/EclipseLink)",
        "JpaDialect",
        "Exception translation with ORM",
      ]},
      {"g":"Marshalling & XML","items":[
        "Object/XML mapping (OXM) abstraction",
        "Marshaller / Unmarshaller",
        "JAXB, Jackson XML support",
      ]},
    ]},
    {"name":"6. Spring Web MVC","tag":"web","groups":[
      {"g":"DispatcherServlet","items":[
        "Servlet web stack overview",
        "DispatcherServlet front controller",
        "WebApplicationContext hierarchy (root + servlet)",
        "Special bean types (HandlerMapping, HandlerAdapter, ViewResolver, etc.)",
        "Web MVC config (defaults)",
        "Servlet config (web.xml / WebApplicationInitializer)",
        "Processing pipeline / request flow",
        "Path matching (PathPattern vs AntPathMatcher)",
        "Interception (HandlerInterceptor)",
        "Exceptions handling chain",
        "View resolution flow",
        "Locale & theme resolution",
        "Multipart resolver (file upload)",
        "Logging request details",
      ]},
      {"g":"Annotated Controllers","items":[
        "@Controller",
        "Request mapping (@RequestMapping)",
        "@GetMapping/@PostMapping/@PutMapping/@DeleteMapping/@PatchMapping",
        "URI patterns & path variables (@PathVariable)",
        "Consumable/producible media types (consumes/produces)",
        "Request parameters & headers conditions",
        "Handler method arguments (full list)",
        "Handler method return values (full list)",
        "@RequestParam",
        "@RequestHeader",
        "@CookieValue",
        "@ModelAttribute (method & argument)",
        "@SessionAttributes / @SessionAttribute",
        "@RequestAttribute",
        "Redirect attributes & flash attributes",
        "@RequestBody & HttpMessageConverter",
        "HttpEntity / RequestEntity",
        "@ResponseBody",
        "ResponseEntity",
        "Jackson JSON serialization views (@JsonView)",
        "Multipart (@RequestPart, MultipartFile)",
        "@RequestMapping on type & method (combining)",
        "@CrossOrigin (CORS)",
        "Model & ModelMap",
        "DataBinder & @InitBinder",
        "Validation in controllers (@Valid + BindingResult)",
        "Exception handling (@ExceptionHandler)",
        "Controller advice (@ControllerAdvice / @RestControllerAdvice)",
        "@ResponseStatus",
      ]},
      {"g":"REST & Functional","items":[
        "@RestController",
        "Building REST APIs",
        "Content negotiation",
        "ResponseBodyEmitter / SseEmitter (streaming)",
        "StreamingResponseBody",
        "Functional endpoints (RouterFunction / HandlerFunction)",
        "ProblemDetail (RFC 9457) & error responses",
        "ErrorResponse / ErrorResponseException",
      ]},
      {"g":"Views & Templating","items":[
        "View & ViewResolver contract",
        "Thymeleaf, FreeMarker, Groovy markup views",
        "JSP & JSTL",
        "Tiles (legacy)",
        "Content negotiation view resolution",
        "PDF/Excel/other document views",
        "Jackson-based JSON/XML views",
        "Redirect & forward views",
      ]},
      {"g":"MVC Config & Other","items":[
        "MVC Java config (@EnableWebMvc / WebMvcConfigurer)",
        "MVC XML namespace (<mvc:annotation-driven>)",
        "Type conversion & formatting config",
        "Validation config",
        "Interceptors config",
        "Content negotiation config",
        "View controllers & view resolvers config",
        "Static resources handling (ResourceHttpRequestHandler)",
        "Resource resolvers & versioning",
        "Default servlet handler",
        "Path matching config",
        "CORS config (global)",
        "Async request processing (Callable, DeferredResult, WebAsyncTask)",
        "HTTP caching (CacheControl, ETag, ShallowEtagHeaderFilter)",
        "Filters (CharacterEncodingFilter, ForwardedHeaderFilter, etc.)",
        "MVC HTTP/2 considerations",
        "Error handling pages",
      ]},
    ]},
    {"name":"7. Spring WebFlux (Reactive)","tag":"reactive","groups":[
      {"g":"Reactive Foundations","items":[
        "Reactive programming overview",
        "Reactive Streams spec (Publisher/Subscriber/Subscription/Processor)",
        "Project Reactor (Mono / Flux)",
        "Backpressure",
        "Imperative vs reactive trade-offs",
        "WebFlux vs WebMVC comparison",
      ]},
      {"g":"WebFlux Programming Models","items":[
        "Annotated controllers (reactive)",
        "Functional endpoints (RouterFunctions)",
        "DispatcherHandler",
        "HttpHandler & adapters (Reactor Netty, Tomcat, Jetty, Undertow, Servlet)",
        "WebHandler API",
        "Reactive @RequestBody / @ResponseBody with Mono/Flux",
        "Reactive exception handling",
        "Server-Sent Events (SSE)",
        "Reactive view technologies",
        "Reactive CORS",
        "WebFilter",
      ]},
      {"g":"Reactive Clients & WebSockets","items":[
        "WebClient (reactive HTTP client)",
        "WebClient request/response, filters, error handling",
        "WebSockets (WebSocketHandler, reactive)",
        "RSocket support",
        "Reactive testing (WebTestClient)",
        "Context propagation (Reactor Context)",
        "Reactive libraries adaptation (RxJava, etc.)",
      ]},
    ]},
    {"name":"8. Integration & Remoting","tag":"integration","groups":[
      {"g":"HTTP Clients","items":[
        "RestClient (synchronous fluent client)",
        "RestTemplate",
        "WebClient (reactive)",
        "HTTP Interface (@HttpExchange declarative clients)",
        "ClientHttpRequestFactory implementations",
        "Interceptors & error handlers",
      ]},
      {"g":"Messaging & Remoting","items":[
        "JMS (JmsTemplate, listeners, @JmsListener)",
        "Message conversion (MessageConverter)",
        "JCA message endpoints",
        "JMX (MBean export, @ManagedResource)",
        "Email (JavaMailSender)",
        "Task execution & scheduling (recap)",
        "Caching abstraction (@Cacheable, @CacheEvict, @CachePut, @Caching)",
        "@EnableCaching & CacheManager",
        "Cache providers (Caffeine, JCache/JSR-107, Redis, etc.)",
        "Observability (Micrometer Observation API)",
        "Tracing & metrics integration",
        "Spring Messaging (Message, MessageChannel, MessageHandler)",
        "STOMP over WebSocket",
        "SockJS fallback",
        "WebSocket (Servlet stack)",
      ]},
    ]},
    {"name":"9. Testing","tag":"testing","groups":[
      {"g":"Unit & Integration Testing","items":[
        "Spring testing philosophy",
        "Unit testing with mock objects",
        "Spring MVC Test mocks (MockHttpServletRequest, etc.)",
        "Integration testing goals",
        "Spring TestContext Framework overview",
        "ApplicationContext caching in tests",
        "Context management (@ContextConfiguration)",
        "Context hierarchies",
        "Dependency injection of test fixtures (@Autowired in tests)",
        "Transaction management in tests (@Transactional, @Commit, @Rollback)",
        "@Sql & test database setup",
        "@DirtiesContext",
        "Test execution listeners (TestExecutionListener)",
        "Test property sources (@TestPropertySource / @DynamicPropertySource)",
        "Active profiles in tests (@ActiveProfiles)",
        "Web contexts (@WebAppConfiguration)",
        "Context customizers",
      ]},
      {"g":"Test Annotations & Tools","items":[
        "JUnit Jupiter support (SpringExtension / @SpringJUnitConfig)",
        "JUnit 4 support (SpringRunner) [legacy]",
        "TestNG support",
        "@Nested test classes",
        "MockMvc & MockMvcBuilders",
        "MockMvc request builders & result matchers",
        "HtmlUnit integration",
        "WebTestClient",
        "Reactive testing with StepVerifier",
        "@MockitoBean / @MockitoSpyBean (test bean overriding)",
        "Testing client-side REST (MockRestServiceServer)",
        "AOT testing support",
        "Testcontainers integration (@ServiceConnection via Boot)",
        "PetClinic / sample-driven testing patterns",
      ]},
    ]},
    {"name":"10. Languages & Kotlin/Groovy","tag":"lang","groups":[
      {"g":"Kotlin","items":[
        "Kotlin support overview",
        "Null-safety with Kotlin",
        "Kotlin extensions (e.g., getBean<T>())",
        "Bean definition DSL (beans { })",
        "Functional bean registration",
        "Router DSL for WebFlux/MVC",
        "Kotlin coroutines support (suspend functions, Flow)",
        "Kotlin & Spring Data",
      ]},
      {"g":"Groovy / Dynamic","items":[
        "Groovy bean definition DSL",
        "Dynamic language beans (Groovy, BeanShell)",
        "Refreshable beans",
      ]},
    ]},
    {"name":"11. Appendix & XML Schemas","tag":"ref","groups":[
      {"g":"XML Configuration Reference","items":[
        "The util schema",
        "The aop schema",
        "The context schema",
        "The jee schema",
        "The jms schema",
        "The lang schema",
        "The task schema",
        "The cache schema",
        "XML application context vs annotation-driven",
        "Migrating javax → jakarta",
        "Upgrading to Spring 6.x",
      ]},
    ]},
  ],
}

BOOT = {
  "file":"spring-boot.html","title":"Spring Boot","logo":"B","cat":"Core",
  "subtitle":"Opinionated, auto-configured, production-ready Spring apps with minimal config.",
  "sections":[
    {"name":"1. Introduction & Getting Started","tag":"intro","groups":[
      {"g":"Overview","items":[
        "What Spring Boot is & its goals",
        "Convention over configuration philosophy",
        "Opinionated 'starter' dependencies",
        "Auto-configuration concept",
        "Embedded servers concept",
        "Production-ready features (Actuator) overview",
        "No code generation & no XML requirement",
        "Spring Boot vs Spring Framework",
        "System requirements (JDK 17+, build tools, servlet containers)",
        "Supported Spring Boot versions & support timeline",
      ]},
      {"g":"Installation & First App","items":[
        "Maven installation & spring-boot-starter-parent",
        "Gradle installation & Spring Boot Gradle plugin",
        "Spring Boot CLI installation",
        "Spring Initializr (start.spring.io)",
        "Creating a first 'Hello World' app",
        "The @SpringBootApplication annotation",
        "Running the application (main method / SpringApplication.run)",
        "Creating an executable (fat/uber) JAR",
        "Running the packaged application",
      ]},
    ]},
    {"name":"2. Build Systems & Structuring","tag":"build","groups":[
      {"g":"Build Systems","items":[
        "Dependency management & the Spring Boot BOM",
        "spring-boot-dependencies BOM",
        "Maven starter parent",
        "Maven without the parent POM",
        "Spring Boot Maven plugin (goals: run, repackage, build-image, etc.)",
        "Gradle plugin (bootRun, bootJar, bootWar)",
        "Gradle dependency management plugin",
        "Ant + Ivy support",
        "Starters list & naming convention (spring-boot-starter-*)",
        "Third-party starters",
      ]},
      {"g":"Code Structure","items":[
        "Using the 'default' package (and why to avoid it)",
        "Locating the main application class",
        "Recommended package layout",
        "Configuration classes & @Import",
        "Importing XML configuration",
        "Component scanning rules",
      ]},
    ]},
    {"name":"3. Auto-Configuration & SpringApplication","tag":"core","groups":[
      {"g":"Auto-configuration","items":[
        "@EnableAutoConfiguration",
        "How auto-configuration works (AutoConfiguration.imports)",
        "Gradually replacing auto-configuration",
        "Disabling specific auto-configuration classes (exclude)",
        "@Conditional annotations (@ConditionalOnClass, @ConditionalOnMissingBean, etc.)",
        "Condition evaluation report (debug)",
        "Creating your own auto-configuration",
        "@AutoConfiguration & ordering (@AutoConfigureBefore/After)",
        "@AutoConfigureOrder",
        "Custom starter (autoconfigure + starter modules)",
      ]},
      {"g":"SpringApplication","items":[
        "SpringApplication class",
        "Startup failure analysis (FailureAnalyzer)",
        "Lazy initialization",
        "Customizing the banner",
        "Customizing SpringApplication (builders, setters)",
        "Fluent builder API (SpringApplicationBuilder)",
        "Application availability (Liveness/Readiness state)",
        "Application events & listeners (lifecycle order)",
        "Web environment detection (SERVLET/REACTIVE/NONE)",
        "Accessing application arguments (ApplicationArguments)",
        "Using the ApplicationRunner / CommandLineRunner",
        "Application exit & exit codes (ExitCodeGenerator)",
        "Admin features (JMX)",
        "Application startup tracking (ApplicationStartup / BufferingApplicationStartup)",
        "Virtual threads (Project Loom) support",
      ]},
    ]},
    {"name":"4. Externalized Configuration","tag":"config","groups":[
      {"g":"Property Sources & Order","items":[
        "Externalized configuration overview",
        "Property source order/precedence (full list)",
        "Command-line properties",
        "JSON application properties (SPRING_APPLICATION_JSON)",
        "application.properties & application.yml",
        "Profile-specific files (application-{profile}.properties)",
        "Config data locations & spring.config.import",
        "Importing additional data (config trees, files, optional)",
        "Property placeholders (${...})",
        "Working with multi-document files (--- separators)",
        "Activation properties (spring.config.activate.on-profile)",
        "Encrypting properties / external secrets (config import)",
        "Environment variables & relaxed binding to env vars",
      ]},
      {"g":"Type-safe Config Properties","items":[
        "@ConfigurationProperties (binding)",
        "JavaBean vs constructor binding (@ConstructorBinding)",
        "Enabling @ConfigurationProperties (@EnableConfigurationProperties / @ConfigurationPropertiesScan)",
        "Relaxed binding rules",
        "Merging complex types (lists, maps)",
        "Properties conversion (Duration, DataSize, etc.)",
        "@ConfigurationProperties validation (@Validated)",
        "@ConfigurationProperties vs @Value",
        "Nested properties",
        "Configuration property metadata (additional-spring-configuration-metadata.json)",
        "@ConfigurationPropertiesBinding custom converters",
      ]},
      {"g":"Profiles","items":[
        "Profiles overview",
        "Adding active profiles",
        "Profile groups",
        "Programmatically setting profiles",
        "Profile-specific configuration files",
        "@Profile on beans",
      ]},
    ]},
    {"name":"5. Logging","tag":"core","groups":[
      {"g":"Logging","items":[
        "Default logging (Logback via Commons Logging)",
        "Log format & console output",
        "File output & rotation",
        "Log levels & configuring per-package",
        "Log groups",
        "Using a log shutdown hook",
        "Custom log configuration (logback-spring.xml, log4j2)",
        "Logback extensions (springProfile, springProperty)",
        "Switching to Log4j2 / Java Util Logging",
        "Color-coded output",
        "Structured logging (ECS, Logstash, GELF)",
        "Profile-specific logging configuration",
      ]},
    ]},
    {"name":"6. Web Applications","tag":"web","groups":[
      {"g":"Servlet Web (Spring MVC)","items":[
        "Spring MVC auto-configuration",
        "HttpMessageConverters customization",
        "Custom JSON serializers/deserializers",
        "MessageCodesResolver",
        "Static content serving",
        "Welcome page",
        "Custom favicon",
        "Path matching & content negotiation",
        "ConfigurableWebBindingInitializer",
        "Template engines (Thymeleaf, FreeMarker, Groovy, Mustache)",
        "Error handling (default error page / whitelabel)",
        "Custom error pages & @ControllerAdvice",
        "ErrorAttributes & ErrorController",
        "CORS support",
        "Spring HATEOAS auto-config",
        "RFC 9457 ProblemDetail support",
      ]},
      {"g":"Embedded Servlet Containers","items":[
        "Embedded Tomcat / Jetty / Undertow",
        "Servlets, Filters, Listeners registration",
        "Servlet context initialization",
        "ConfigurableServletWebServerFactory / WebServerFactoryCustomizer",
        "Customizing embedded server (port, context-path, etc.)",
        "Programmatic customization",
        "JSP limitations",
        "Enabling HTTP/2",
        "SSL/TLS configuration & SSL bundles",
        "Graceful shutdown",
      ]},
      {"g":"Reactive Web (WebFlux)","items":[
        "Spring WebFlux auto-configuration",
        "WebFlux error handling",
        "Embedded reactive server (Reactor Netty)",
        "WebClient auto-configuration & customization",
        "Reactive HTTP codecs",
        "Reactive static resources",
      ]},
      {"g":"Other Web Features","items":[
        "RestClient auto-configuration",
        "RestTemplate auto-configuration (RestTemplateBuilder)",
        "Client HTTP request factories",
        "WebSockets support",
        "Spring Session auto-configuration",
        "GraphQL support",
        "Jersey (JAX-RS) support",
      ]},
    ]},
    {"name":"7. Data & Messaging","tag":"data","groups":[
      {"g":"SQL Databases","items":[
        "DataSource configuration & connection pools (HikariCP, Tomcat, DBCP2)",
        "Embedded database support",
        "Connection to a production database",
        "JNDI DataSource",
        "JdbcTemplate / JdbcClient auto-config",
        "JPA & Spring Data JPA auto-config",
        "Entity classes & repositories",
        "Hibernate (spring.jpa.hibernate.ddl-auto, naming strategies)",
        "Open EntityManager in View",
        "Spring Data JDBC",
        "Spring Data R2DBC",
        "jOOQ support",
        "Database initialization (schema.sql / data.sql)",
        "Flyway migrations",
        "Liquibase migrations",
        "@ServiceConnection & Testcontainers / Docker Compose",
      ]},
      {"g":"NoSQL","items":[
        "Redis (Lettuce/Jedis)",
        "MongoDB",
        "Neo4j",
        "Elasticsearch",
        "Cassandra",
        "Couchbase",
        "LDAP / embedded LDAP",
        "InfluxDB (legacy)",
      ]},
      {"g":"Messaging","items":[
        "JMS (ActiveMQ Artemis)",
        "AMQP (RabbitMQ)",
        "Apache Kafka",
        "Apache Pulsar",
        "RSocket",
        "Spring Integration auto-config",
        "WebSocket messaging (STOMP)",
        "@JmsListener / @RabbitListener / @KafkaListener auto-config",
      ]},
      {"g":"Caching","items":[
        "Caching auto-configuration",
        "Supported cache providers (Generic, JCache, Hazelcast, Infinispan, Couchbase, Redis, Caffeine, Cache2k, Simple)",
        "Customizing the cache configuration",
      ]},
    ]},
    {"name":"8. Production-Ready (Actuator)","tag":"actuator","groups":[
      {"g":"Endpoints","items":[
        "Enabling Actuator (spring-boot-starter-actuator)",
        "Built-in endpoints list (health, info, metrics, env, beans, mappings, etc.)",
        "Exposing endpoints (web/JMX include/exclude)",
        "Securing endpoints",
        "Endpoint paths & base path (management.endpoints.web.base-path)",
        "CORS for endpoints",
        "Custom endpoints (@Endpoint, @ReadOperation, @WriteOperation, @DeleteOperation)",
        "@WebEndpoint / @JmxEndpoint / @ControllerEndpoint",
        "Hypermedia for endpoints (/actuator discovery)",
      ]},
      {"g":"Health, Info, Metrics","items":[
        "Health endpoint & HealthIndicator",
        "Health groups",
        "Auto-configured HealthIndicators",
        "Custom HealthIndicator",
        "Liveness & readiness probes (Kubernetes)",
        "Info endpoint & InfoContributor",
        "Build & git info (build-info, git.properties)",
        "Metrics with Micrometer",
        "Supported monitoring systems (Prometheus, Graphite, Datadog, etc.)",
        "Custom metrics (Counter, Gauge, Timer, etc.)",
        "@Timed / Observation API",
        "Supported metrics (JVM, system, HTTP, DataSource, cache, etc.)",
        "Distributed tracing (Micrometer Tracing — Brave/OpenTelemetry)",
        "Loggers endpoint (runtime log-level changes)",
        "HTTP exchanges recording",
        "Auditing (AuditEventRepository)",
        "Process monitoring & PID files",
        "Cloud Foundry support",
      ]},
    ]},
    {"name":"9. Testing","tag":"testing","groups":[
      {"g":"Testing Support","items":[
        "spring-boot-starter-test contents (JUnit 5, AssertJ, Hamcrest, Mockito, JSONassert, JsonPath)",
        "@SpringBootTest",
        "WebEnvironment modes (MOCK, RANDOM_PORT, DEFINED_PORT, NONE)",
        "Detecting test configuration (@SpringBootConfiguration)",
        "Excluding test config & user config",
        "@TestConfiguration",
        "Mocking beans (@MockitoBean / @MockitoSpyBean)",
        "Auto-configured tests (test slices)",
        "@WebMvcTest",
        "@WebFluxTest",
        "@DataJpaTest",
        "@DataJdbcTest / @JdbcTest",
        "@DataR2dbcTest",
        "@DataMongoTest / @DataRedisTest / @DataNeo4jTest / etc.",
        "@JsonTest",
        "@RestClientTest",
        "@JooqTest",
        "@GraphQlTest",
        "@RestDocs auto-config (@AutoConfigureRestDocs)",
        "TestRestTemplate",
        "Auto-configured WebTestClient",
        "Auto-configured MockMvc / MockMvcTester",
        "@TestPropertySource & @DynamicPropertySource",
        "Testcontainers (@Testcontainers, @ServiceConnection)",
        "Docker Compose support in tests",
        "@TestConfiguration vs @Import",
        "Testing application arguments & startup",
        "TestContext bean override",
      ]},
    ]},
    {"name":"10. Packaging, Deployment & Native","tag":"deploy","groups":[
      {"g":"Packaging & Container","items":[
        "Executable JARs (the nested JAR format / Loader)",
        "Launcher classes (JarLauncher / WarLauncher / PropertiesLauncher)",
        "Layered JARs",
        "Layertools & extracting layers",
        "Building WAR files (traditional deployment)",
        "SpringBootServletInitializer",
        "Efficient container images",
        "Dockerfiles & layered images",
        "Buildpacks (Cloud Native Buildpacks / Paketo)",
        "spring-boot:build-image goal",
        "CDS (Class Data Sharing) & training runs",
      ]},
      {"g":"Native Image (GraalVM)","items":[
        "GraalVM Native Image introduction",
        "Spring Ahead-of-Time processing",
        "spring-boot-starter-parent native profile",
        "Building a native image with Buildpacks",
        "Building with GraalVM Native Build Tools",
        "Runtime hints & reflection config",
        "Testing AOT / native",
        "Known limitations of native images",
        "Conditions & native limitations",
      ]},
      {"g":"Deployment","items":[
        "Deploying to the cloud (Cloud Foundry, Kubernetes, Heroku, AWS, Azure, GCP)",
        "Installing as a Unix/Linux/Windows service (systemd, init.d)",
        "Graceful shutdown in production",
        "Configuring for production",
      ]},
    ]},
    {"name":"11. CLI, DevTools & Extras","tag":"tools","groups":[
      {"g":"Developer Tooling","items":[
        "Spring Boot DevTools overview",
        "Automatic restart",
        "LiveReload",
        "Property defaults in DevTools",
        "Remote applications (remote debug/restart)",
        "Global DevTools settings",
        "Disabling DevTools in production",
      ]},
      {"g":"CLI & Misc","items":[
        "Spring Boot CLI commands",
        "Spring Initializr usage from CLI / IDE",
        "Hot swapping",
        "WebSockets DevTools considerations",
        "Internationalization (MessageSource auto-config)",
        "JSON (Jackson / Gson / JSON-B) auto-config",
        "Task execution & scheduling auto-config (TaskExecutor/TaskScheduler)",
        "Validation (Bean Validation) auto-config",
        "Calling REST services (RestClient/WebClient builders)",
        "Sending email auto-config",
        "Distributed transactions (JTA) — legacy",
        "Hazelcast auto-config",
        "Quartz Scheduler",
        "Spring Boot Properties Migrator",
      ]},
    ]},
  ],
}

PROJECTS = [FRAMEWORK, BOOT]
