# -*- coding: utf-8 -*-
"""Spring Data (all store modules) + Spring Cloud (all sub-projects)."""

DATA = {
  "file":"spring-data.html","title":"Spring Data","logo":"D","cat":"Data & Cloud",
  "subtitle":"Consistent data access across relational, NoSQL, map-reduce & cloud stores. Every module as a section.",
  "sections":[
    {"name":"1. Spring Data Commons (core)","tag":"commons","groups":[
      {"g":"Core Concepts","items":[
        "Spring Data mission & umbrella overview",
        "Repository abstraction",
        "Repository<T,ID> base interface",
        "CrudRepository",
        "ListCrudRepository",
        "PagingAndSortingRepository / ListPagingAndSortingRepository",
        "Store-specific repositories (JpaRepository, MongoRepository, etc.)",
        "Defining repository interfaces",
        "Fine-tuning repository definition (@RepositoryDefinition, @NoRepositoryBean)",
        "Null handling (Optional, @Nullable)",
        "CompletableFuture / reactive return types",
      ]},
      {"g":"Query Methods","items":[
        "Query derivation from method names",
        "Query lookup strategies (CREATE, USE_DECLARED_QUERY, CREATE_IF_NOT_FOUND)",
        "Property expressions & nested properties",
        "Supported keywords (And, Or, Between, LessThan, Like, In, etc.)",
        "Special parameter handling (Pageable, Sort, Limit)",
        "Paging & Slice & Page & Window (keyset)",
        "Sort & TypedSort & Sort.TypedSort",
        "Limiting query results (First, Top)",
        "@Query annotated queries",
        "Named queries",
        "Streaming query results (Stream<T>)",
        "Async query results",
        "Projections (interface-based & class-based DTO)",
        "Open vs closed projections",
        "Dynamic projections",
      ]},
      {"g":"Configuration & Extensions","items":[
        "Creating repository instances (Java/XML config)",
        "@EnableJpaRepositories & enable annotations",
        "Custom repository implementations (fragments)",
        "Customizing the base repository",
        "Publishing events from aggregate roots (@DomainEvents)",
        "Spring Data extensions (web support)",
        "@EnableSpringDataWebSupport",
        "DomainClassConverter",
        "HandlerMethodArgumentResolvers (Pageable/Sort)",
        "Hypermedia paging (PagedResourcesAssembler)",
        "Web databinding & projections",
        "Querydsl integration (QuerydslPredicateExecutor)",
        "Auditing (@CreatedDate, @LastModifiedDate, @CreatedBy, @LastModifiedBy)",
        "AuditorAware",
        "Entity callbacks (BeforeConvertCallback, etc.)",
        "Object mapping fundamentals",
        "Identifier generation",
        "Custom conversions (Converter registration)",
      ]},
    ]},
    {"name":"2. Spring Data JPA","tag":"jpa","groups":[
      {"g":"Repositories & Queries","items":[
        "JpaRepository / JpaSpecificationExecutor",
        "Persisting & deleting entities",
        "Derived query methods (JPA)",
        "@Query with JPQL",
        "@Query with native SQL (nativeQuery=true)",
        "Named parameters & positional parameters",
        "@Param",
        "SpEL in queries",
        "Modifying queries (@Modifying)",
        "Derived delete queries",
        "Query by Example (QBE)",
        "Specifications (Criteria API)",
        "Querydsl with JPA",
        "Projections (DTO & interface)",
        "Named entity graphs (@EntityGraph)",
        "Fetch & load graphs",
        "Stored procedures (@Procedure)",
        "Sorting & paging in JPA",
        "Keyset pagination (scroll)",
      ]},
      {"g":"Configuration & Advanced","items":[
        "Bootstrapping JPA repositories (deferred/lazy)",
        "Persistence context & EntityManager",
        "@Lock (pessimistic/optimistic locking)",
        "@QueryHints",
        "Transactional query methods",
        "Auditing with JPA (@EnableJpaAuditing)",
        "Envers integration (RevisionRepository)",
        "Hibernate-specific features",
        "Custom JPA repository implementation",
        "@DynamicUpdate / @DynamicInsert (Hibernate)",
        "Naming strategies",
      ]},
    ]},
    {"name":"3. Spring Data JDBC","tag":"jdbc","groups":[
      {"g":"JDBC","items":[
        "Domain-driven design & aggregates philosophy",
        "CrudRepository for JDBC",
        "Aggregate roots & references",
        "Entity persistence & mapping",
        "@Id, @Table, @Column, @MappedCollection",
        "Embedded entities (@Embedded)",
        "Query methods & @Query (native SQL)",
        "JdbcAggregateTemplate",
        "Custom conversions",
        "Optimistic locking (@Version)",
        "ID generation",
        "Auditing",
        "Lifecycle events / entity callbacks",
        "Schema requirements & limitations vs JPA",
        "MyBatis integration",
      ]},
    ]},
    {"name":"4. Spring Data R2DBC","tag":"r2dbc","groups":[
      {"g":"Reactive Relational","items":[
        "R2DBC reactive overview",
        "ReactiveCrudRepository",
        "R2dbcEntityTemplate",
        "DatabaseClient (reactive)",
        "Fluent query API (Criteria)",
        "Mapping & conversions",
        "Reactive transactions",
        "Auditing (reactive)",
        "Drivers (Postgres, MySQL, MSSQL, H2, MariaDB)",
        "Connection factories & pooling",
      ]},
    ]},
    {"name":"5. Spring Data MongoDB","tag":"mongo","groups":[
      {"g":"MongoDB","items":[
        "MongoTemplate / ReactiveMongoTemplate",
        "MongoRepository / ReactiveMongoRepository",
        "Connecting (MongoClient settings)",
        "Document mapping (@Document, @Id, @Field, @Indexed)",
        "Derived & @Query (JSON) queries",
        "Criteria & Query objects",
        "Aggregation framework support",
        "GeoSpatial queries",
        "Full-text search",
        "GridFS support",
        "Index management",
        "Map-reduce",
        "Change streams (reactive)",
        "Transactions (multi-document)",
        "Auditing & entity callbacks",
        "Optimistic locking (@Version)",
        "JSON Schema validation",
        "Time series collections",
        "Client-side field-level encryption",
      ]},
    ]},
    {"name":"6. Spring Data Redis","tag":"redis","groups":[
      {"g":"Redis","items":[
        "RedisConnectionFactory (Lettuce / Jedis)",
        "RedisTemplate / StringRedisTemplate",
        "ReactiveRedisTemplate",
        "Serializers (String, JSON, JDK, etc.)",
        "Opsfor* operations (Value/List/Set/ZSet/Hash/Geo/HyperLogLog/Stream)",
        "Redis Repositories (@RedisHash)",
        "Secondary indexes",
        "Time to live (@TimeToLive)",
        "Pub/Sub messaging (MessageListener)",
        "Redis Streams",
        "Transactions & pipelining",
        "Redis Cluster support",
        "Redis Sentinel support",
        "Caching with Redis (RedisCacheManager)",
        "Distributed locks",
        "Scripting (Lua)",
      ]},
    ]},
    {"name":"7. Spring Data Elasticsearch","tag":"es","groups":[
      {"g":"Elasticsearch","items":[
        "ElasticsearchOperations / ElasticsearchTemplate",
        "ReactiveElasticsearchOperations",
        "ElasticsearchRepository",
        "Document mapping (@Document, @Field, @Id)",
        "Index & mapping management",
        "Criteria & CriteriaQuery",
        "@Query (JSON) & string queries",
        "Native queries (NativeQuery)",
        "Highlighting",
        "Aggregations",
        "Sorting, paging, scroll/search-after",
        "Routing",
        "Join/parent-child",
        "Geo queries",
        "Auditing",
      ]},
    ]},
    {"name":"8. Spring Data for Apache Cassandra","tag":"cassandra","groups":[
      {"g":"Cassandra","items":[
        "CassandraTemplate / ReactiveCassandraTemplate",
        "CassandraRepository / ReactiveCassandraRepository",
        "Connecting (CqlSession)",
        "Mapping (@Table, @PrimaryKey, @Column, @PrimaryKeyClass)",
        "Composite & partition/clustering keys",
        "CQL queries & @Query",
        "Query derivation",
        "User-defined types (UDT)",
        "Schema management",
        "Consistency levels",
        "Lightweight transactions",
        "Paging",
      ]},
    ]},
    {"name":"9. Spring Data Neo4j","tag":"neo4j","groups":[
      {"g":"Neo4j","items":[
        "Neo4jTemplate / ReactiveNeo4jTemplate",
        "Neo4jRepository / ReactiveNeo4jRepository",
        "Node & relationship mapping (@Node, @Relationship, @Id)",
        "Cypher queries & @Query",
        "Cypher-DSL",
        "Projections",
        "Derived finder methods",
        "Auditing",
        "Optimistic locking",
        "Custom conversions",
      ]},
    ]},
    {"name":"10. Other Store Modules","tag":"misc","groups":[
      {"g":"Couchbase / LDAP / KeyValue","items":[
        "Spring Data Couchbase (template, repositories, N1QL)",
        "Spring Data LDAP (LdapRepository, @Entry)",
        "Spring Data KeyValue (in-memory, Map-based)",
        "Spring Data Envers (revision repositories)",
        "Spring Data JPA + QueryDSL integration",
      ]},
      {"g":"Spring Data REST","items":[
        "Exposing repositories as REST (HAL)",
        "@RepositoryRestResource",
        "Default exposure & detection strategies",
        "Customizing item/collection resources",
        "Projections & excerpts (@Projection)",
        "Conditional GET (ETag/Last-Modified)",
        "Custom controllers (@RepositoryRestController)",
        "Events (RepositoryEventHandler / ApplicationListener)",
        "Validation",
        "HAL Explorer / HAL Browser",
        "Metadata (ALPS / JSON Schema)",
        "Security with Spring Data REST",
      ]},
      {"g":"Spring Data for Apache Geode / GemFire","items":[
        "Region & template configuration",
        "OQL queries",
        "Repositories for Geode/GemFire",
      ]},
    ]},
  ],
}

CLOUD = {
  "file":"spring-cloud.html","title":"Spring Cloud","logo":"C","cat":"Data & Cloud",
  "subtitle":"Tools for distributed systems: config, discovery, gateway, resilience, messaging, tracing. Every sub-project as a section.",
  "sections":[
    {"name":"1. Spring Cloud Overview","tag":"intro","groups":[
      {"g":"Foundations","items":[
        "What Spring Cloud is & the 12-factor / cloud-native context",
        "Release trains & version naming (calendar versions)",
        "Spring Cloud BOM",
        "Spring Cloud Commons (shared abstractions)",
        "Bootstrap context & spring.cloud.bootstrap",
        "Spring Cloud Context (lifecycle, refresh)",
        "@RefreshScope & runtime refresh",
        "Endpoints (/refresh, /restart, /pause, /resume)",
        "Service Registry abstraction (ServiceRegistry/Registration)",
        "DiscoveryClient abstraction",
        "@EnableDiscoveryClient",
        "ServiceInstance & InstanceInfo",
      ]},
    ]},
    {"name":"2. Spring Cloud Config","tag":"config","groups":[
      {"g":"Config Server & Client","items":[
        "Centralized external configuration concept",
        "Config Server (@EnableConfigServer)",
        "Git backend",
        "File system / native backend",
        "Vault backend",
        "JDBC / Redis / AWS S3 backends",
        "Composite backends",
        "Environment repository & property resolution",
        "Encryption & decryption (symmetric/asymmetric)",
        "Serving plain text & binary files",
        "Health indicator & security",
        "Config Client (importing config via spring.config.import)",
        "Fail-fast & retry",
        "Refreshing config (@RefreshScope, /actuator/refresh)",
        "Spring Cloud Bus for broadcast refresh",
      ]},
    ]},
    {"name":"3. Service Discovery (Netflix Eureka & others)","tag":"discovery","groups":[
      {"g":"Eureka","items":[
        "Eureka Server (@EnableEurekaServer)",
        "Eureka Client registration & discovery",
        "Instance & client configuration",
        "Self-preservation mode",
        "Eureka peer awareness / HA",
        "Health checks & status",
        "Region & zone awareness",
      ]},
      {"g":"Consul / Zookeeper","items":[
        "Spring Cloud Consul (discovery & config)",
        "Consul service registration & health checks",
        "Consul KV config",
        "Spring Cloud Zookeeper (discovery & config)",
        "Zookeeper dependencies & service registry",
      ]},
    ]},
    {"name":"4. Routing & Load Balancing","tag":"routing","groups":[
      {"g":"Spring Cloud Gateway","items":[
        "Gateway overview (reactive, Netty)",
        "Routes, Predicates & Filters model",
        "Route predicate factories (Path, Host, Method, Header, Query, etc.)",
        "GatewayFilter factories (AddRequestHeader, RewritePath, Retry, etc.)",
        "Global filters",
        "Circuit breaker filter",
        "Rate limiting (RequestRateLimiter / Redis)",
        "TLS & SSL",
        "Route metadata & configuration (Java DSL vs YAML)",
        "Actuator API for gateway",
        "Gateway MVC (servlet variant)",
        "CORS configuration",
      ]},
      {"g":"Load Balancer","items":[
        "Spring Cloud LoadBalancer (client-side)",
        "@LoadBalanced RestTemplate / WebClient / RestClient",
        "ReactorLoadBalancer & ServiceInstanceListSupplier",
        "Load balancing algorithms (round-robin, random)",
        "Zone-based & hint-based balancing",
        "Caching & health checks",
        "Retrying failed requests",
      ]},
      {"g":"OpenFeign","items":[
        "Declarative REST clients (@FeignClient)",
        "@EnableFeignClients",
        "Feign annotations & inheritance",
        "Custom configuration (encoder/decoder/contract)",
        "Feign + LoadBalancer",
        "Feign + Circuit Breaker fallbacks",
        "Request/response compression",
        "Logging levels",
        "Feign error decoding",
      ]},
    ]},
    {"name":"5. Resilience & Circuit Breaking","tag":"resilience","groups":[
      {"g":"Circuit Breaker","items":[
        "Spring Cloud Circuit Breaker abstraction",
        "Resilience4j implementation",
        "CircuitBreakerFactory & customizers",
        "Circuit breaker states (closed/open/half-open)",
        "Bulkhead",
        "Rate limiter",
        "Retry",
        "Time limiter",
        "Fallbacks",
        "Spring Retry (@Retryable, @Recover)",
        "Spring AOP-based retry",
      ]},
    ]},
    {"name":"6. Messaging — Stream & Bus","tag":"messaging","groups":[
      {"g":"Spring Cloud Stream","items":[
        "Event-driven microservices concept",
        "Binders abstraction (Kafka, RabbitMQ, etc.)",
        "Functional programming model (Supplier/Function/Consumer)",
        "Bindings & destinations",
        "Consumer groups & partitioning",
        "Content type negotiation",
        "Error handling & dead-letter queues",
        "Polled consumers",
        "Reactive functions",
        "Stream testing (TestChannelBinder)",
        "Multiple binders & multi-binding",
        "Batch consumers",
      ]},
      {"g":"Spring Cloud Bus","items":[
        "Linking nodes via a message broker",
        "Broadcasting state changes (config refresh)",
        "Custom events on the bus",
        "Tracing bus events",
      ]},
      {"g":"Spring Cloud Function","items":[
        "Functions as first-class (Supplier/Function/Consumer)",
        "Function composition & routing",
        "Function deployment (web, stream, serverless adapters)",
        "AWS Lambda / Azure Functions / GCF adapters",
        "Function catalog & registration",
      ]},
    ]},
    {"name":"7. Observability — Tracing & Sleuth","tag":"tracing","groups":[
      {"g":"Tracing","items":[
        "Distributed tracing concepts (spans, traces)",
        "Micrometer Tracing (successor to Sleuth)",
        "Brave / Zipkin integration",
        "OpenTelemetry integration",
        "Propagation (W3C, B3)",
        "Sampling",
        "Instrumentation (web, messaging, scheduling)",
        "Correlation IDs in logs",
        "Legacy Spring Cloud Sleuth migration",
      ]},
    ]},
    {"name":"8. Security, Vault & Kubernetes","tag":"platform","groups":[
      {"g":"Vault & Security","items":[
        "Spring Cloud Vault (secrets as config)",
        "Vault backends (KV, database, PKI, AWS, etc.)",
        "Token & authentication methods",
        "Lease renewal & rotation",
        "Spring Cloud Security (legacy, OAuth2 relay)",
      ]},
      {"g":"Kubernetes","items":[
        "Spring Cloud Kubernetes overview",
        "ConfigMap & Secrets PropertySource",
        "Service discovery via Kubernetes API",
        "Kubernetes-native load balancing",
        "Reloading config on change",
        "Leader election",
        "Spring Cloud Kubernetes Config Server",
      ]},
    ]},
    {"name":"9. Contracts, Tasks & Data Flow","tag":"extras","groups":[
      {"g":"Contract & Task","items":[
        "Spring Cloud Contract (consumer-driven contracts)",
        "Contract DSL (Groovy/YAML)",
        "Stub runner & WireMock",
        "Producer & consumer side testing",
        "Spring Cloud Task (short-lived microservices/batch)",
        "TaskExecution & repository",
        "Task events & listeners",
      ]},
      {"g":"Data Flow & Pipelines","items":[
        "Spring Cloud Data Flow overview (orchestration)",
        "Streams & tasks in Data Flow",
        "Spring Cloud Skipper (deployment)",
        "Spring Cloud Deployer abstraction",
      ]},
      {"g":"Cloud Provider Integrations","items":[
        "Spring Cloud AWS (S3, SQS, SNS, Parameter Store, Secrets Manager)",
        "Spring Cloud Azure",
        "Spring Cloud GCP",
        "Spring Cloud Gateway for Kubernetes / Tanzu",
      ]},
    ]},
  ],
}

PROJECTS = [DATA, CLOUD]
