# -*- coding: utf-8 -*-
"""Web Development — exhaustive micro-topics spanning the full stack: how the web
works, HTML, CSS, JavaScript, TypeScript, the DOM & browser APIs, HTTP &
networking, frontend architecture & frameworks, state management, styling systems,
build tooling, modules & packages, backend web dev, APIs (REST/GraphQL/gRPC/
WebSocket), data & persistence, auth, web security, performance, accessibility,
SEO, PWAs, rendering strategies, testing, DevOps/hosting, web standards — and how
the Spring ecosystem helps. Single self-contained checklist file.
"""

WEBDEV = {
  "file":"webdev.html","title":"Web Development","logo":"W","cat":"Web Development",
  "subtitle":"Every micro-topic of web development — HTML, CSS, JS/TS, the DOM, HTTP, frontend frameworks, state, build tools, backend, APIs, auth, security, performance, a11y, SEO, PWAs, rendering, testing, deployment — and how Spring helps.",
  "sections":[

    {"name":"1. How the Web Works","tag":"fundamentals","groups":[
      {"g":"Core Concepts","items":[
        "Client–server model",
        "Frontend vs backend vs full-stack",
        "Web page vs web site vs web app",
        "Static vs dynamic web pages",
        "Request–response cycle",
        "Stateless nature of HTTP",
        "URI vs URL vs URN",
        "URL anatomy (scheme, host, port, path, query, fragment)",
        "Origin (scheme + host + port)",
        "Web browser as a user agent",
        "Browser engine vs JS engine vs rendering engine",
        "Internet vs World Wide Web",
        "How a browser loads a page end-to-end",
      ]},
      {"g":"Naming & Addressing","items":[
        "Domain names & the domain hierarchy",
        "DNS resolution (recursive & authoritative)",
        "DNS record types (A, AAAA, CNAME, MX, TXT, NS, SOA)",
        "TTL & DNS caching",
        "IP addresses (IPv4 vs IPv6)",
        "Ports & well-known ports",
        "Registrars, nameservers & propagation",
        "Hosts file & local overrides",
      ]},
      {"g":"Transport & Delivery","items":[
        "TCP/IP model & OSI model",
        "TCP three-way handshake",
        "UDP vs TCP",
        "TLS/SSL handshake",
        "Certificates, CAs & chain of trust",
        "HTTPS & encryption in transit",
        "Content Delivery Networks (CDN)",
        "Edge servers & points of presence",
        "Latency, bandwidth & round-trip time (RTT)",
        "Reverse proxy & load balancer basics",
      ]},
    ]},

    {"name":"2. HTTP & Networking","tag":"http","groups":[
      {"g":"HTTP Protocol","items":[
        "HTTP request structure (method, path, headers, body)",
        "HTTP response structure (status line, headers, body)",
        "HTTP methods (GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS)",
        "Safe vs idempotent methods",
        "HTTP status codes (1xx–5xx) & their meaning",
        "Common headers (Content-Type, Accept, Authorization, User-Agent)",
        "Request vs response vs entity headers",
        "Content negotiation (Accept, Accept-Language, Accept-Encoding)",
        "MIME types / media types",
        "Query strings vs path params vs body",
        "URL encoding / percent-encoding",
        "Connection management (keep-alive)",
      ]},
      {"g":"HTTP Versions","items":[
        "HTTP/0.9, 1.0, 1.1",
        "HTTP/1.1 persistent connections & pipelining",
        "Head-of-line blocking",
        "HTTP/2 (multiplexing, header compression, server push)",
        "HTTP/3 & QUIC (UDP-based)",
        "0-RTT & connection migration in QUIC",
      ]},
      {"g":"Caching","items":[
        "Cache-Control directives (max-age, no-store, no-cache, private, public)",
        "ETag & If-None-Match (validation)",
        "Last-Modified & If-Modified-Since",
        "Expires header",
        "Strong vs weak validators",
        "Conditional requests & 304 Not Modified",
        "Browser cache vs proxy cache vs CDN cache",
        "Cache busting & content hashing",
        "Vary header",
      ]},
      {"g":"State & Sessions","items":[
        "Cookies (Set-Cookie, attributes)",
        "Cookie attributes (HttpOnly, Secure, SameSite, Domain, Path, Max-Age)",
        "Session vs persistent cookies",
        "Server-side sessions vs token-based state",
        "localStorage vs sessionStorage vs cookies",
        "IndexedDB",
        "Cache Storage API",
      ]},
      {"g":"Cross-Origin","items":[
        "Same-Origin Policy (SOP)",
        "CORS (Cross-Origin Resource Sharing)",
        "Simple vs preflighted requests",
        "Preflight OPTIONS request",
        "Access-Control-Allow-* headers",
        "Credentialed requests & withCredentials",
        "CORS vs CORB vs CORP",
        "JSONP (legacy workaround)",
      ]},
    ]},

    {"name":"3. HTML","tag":"html","groups":[
      {"g":"Document Fundamentals","items":[
        "HTML document structure (<!DOCTYPE>, html, head, body)",
        "Elements, tags & attributes",
        "Void / self-closing elements",
        "Global attributes (id, class, style, title, lang, hidden)",
        "data-* custom attributes",
        "Character encoding (meta charset utf-8)",
        "The viewport meta tag",
        "HTML comments",
        "Block vs inline vs inline-block elements",
        "Nesting rules & valid content models",
      ]},
      {"g":"Semantic HTML","items":[
        "Semantic vs non-semantic elements",
        "header, nav, main, section, article, aside, footer",
        "Headings (h1–h6) & document outline",
        "Paragraphs, lists (ul, ol, dl)",
        "figure & figcaption",
        "time, mark, abbr, cite, address",
        "details & summary (native disclosure)",
        "dialog element",
        "Landmark roles & document semantics",
      ]},
      {"g":"Text, Links & Media","items":[
        "Anchor links (href, target, rel)",
        "rel attributes (noopener, noreferrer, nofollow)",
        "Images (img, alt, srcset, sizes)",
        "Responsive images & the picture element",
        "Lazy loading (loading=lazy)",
        "Audio & video elements",
        "track element & captions",
        "iframe & sandboxing",
        "Embedding (embed, object)",
        "SVG inline & external",
        "Canvas element",
      ]},
      {"g":"Forms","items":[
        "form element (action, method, enctype)",
        "Input types (text, email, number, date, file, range, color, etc.)",
        "label & input association",
        "textarea, select, option, optgroup",
        "Buttons (submit, reset, button)",
        "fieldset & legend",
        "Form validation attributes (required, pattern, min, max, step)",
        "Constraint Validation API",
        "Form submission & FormData",
        "autocomplete & autofill",
        "Accessible form patterns",
      ]},
      {"g":"Metadata & Head","items":[
        "title element",
        "meta description & keywords",
        "Open Graph & Twitter Card meta tags",
        "link element (stylesheets, icons, preload, prefetch)",
        "favicon & app icons",
        "Canonical link",
        "base element",
        "script element (defer, async, type=module)",
      ]},
      {"g":"Templates & Components","items":[
        "template element",
        "slot element",
        "Web Components overview",
        "Custom Elements API",
        "Shadow DOM",
        "HTML imports (deprecated) & alternatives",
      ]},
    ]},

    {"name":"4. CSS","tag":"css","groups":[
      {"g":"Fundamentals","items":[
        "CSS syntax (selectors, declarations, properties, values)",
        "Inline vs internal vs external CSS",
        "The cascade",
        "Specificity & specificity calculation",
        "Inheritance & inheritable properties",
        "!important & when to avoid it",
        "Source order & origin",
        "Initial, inherit, unset, revert keywords",
        "Comments in CSS",
      ]},
      {"g":"Selectors","items":[
        "Type, class, id, universal selectors",
        "Attribute selectors",
        "Descendant, child, sibling combinators",
        "Pseudo-classes (:hover, :focus, :nth-child, :not, :is, :where)",
        "Pseudo-elements (::before, ::after, ::marker, ::selection)",
        ":has() relational selector",
        "Functional pseudo-classes (:is, :where, :not specificity)",
        "Structural & state pseudo-classes",
      ]},
      {"g":"Box Model & Layout","items":[
        "The box model (content, padding, border, margin)",
        "box-sizing (content-box vs border-box)",
        "Margin collapsing",
        "Display values (block, inline, inline-block, none)",
        "Positioning (static, relative, absolute, fixed, sticky)",
        "Stacking context & z-index",
        "Overflow & scrolling",
        "Float & clear (legacy)",
        "Containing block",
      ]},
      {"g":"Flexbox","items":[
        "Flex container & flex items",
        "flex-direction & flex-wrap",
        "justify-content, align-items, align-content",
        "flex-grow, flex-shrink, flex-basis",
        "align-self & order",
        "gap in flexbox",
        "Common flexbox layout patterns",
      ]},
      {"g":"Grid","items":[
        "Grid container & grid items",
        "grid-template-columns / rows",
        "fr unit & minmax()",
        "repeat() & auto-fill / auto-fit",
        "Grid lines, areas & named areas",
        "grid-gap / gap",
        "Implicit vs explicit grid",
        "Alignment in grid (justify/align items/content)",
        "Subgrid",
      ]},
      {"g":"Responsive Design","items":[
        "Media queries (min-width, max-width, features)",
        "Mobile-first vs desktop-first",
        "Breakpoints strategy",
        "Container queries",
        "Relative units (%, em, rem, vw, vh, vmin, vmax)",
        "clamp(), min(), max()",
        "Fluid typography",
        "prefers-color-scheme & prefers-reduced-motion",
        "Responsive images integration",
      ]},
      {"g":"Visual Styling","items":[
        "Colors (hex, rgb, hsl, hwb, named, currentColor)",
        "Color functions & color-mix()",
        "Backgrounds (color, image, gradient, position, size)",
        "Gradients (linear, radial, conic)",
        "Borders & border-radius",
        "Box shadow & text shadow",
        "Opacity & alpha transparency",
        "Filters (blur, brightness, drop-shadow)",
        "backdrop-filter",
        "Blend modes (mix-blend-mode, background-blend-mode)",
      ]},
      {"g":"Typography","items":[
        "Font properties (family, size, weight, style)",
        "Web fonts & @font-face",
        "font-display & FOUT/FOIT",
        "Variable fonts",
        "Line-height, letter-spacing, word-spacing",
        "Text alignment & decoration",
        "text-overflow & ellipsis",
        "Writing modes & direction (rtl)",
        "Font loading strategies",
      ]},
      {"g":"Transitions & Animation","items":[
        "transition property & timing functions",
        "transform (translate, rotate, scale, skew)",
        "transform-origin & 3D transforms",
        "@keyframes & animation property",
        "animation-fill-mode, delay, iteration",
        "will-change & GPU acceleration",
        "Scroll-driven animations",
        "View Transitions API",
        "Reduced-motion accessibility",
      ]},
      {"g":"Modern CSS","items":[
        "Custom properties (CSS variables)",
        "calc()",
        "Logical properties (margin-inline, padding-block)",
        "Cascade layers (@layer)",
        "Nesting (native CSS nesting)",
        "@supports feature queries",
        "Aspect-ratio property",
        "Accent-color & form styling",
        "@property & typed custom properties",
        "Anchor positioning",
      ]},
      {"g":"CSS Architecture","items":[
        "BEM (Block Element Modifier)",
        "OOCSS & SMACSS",
        "ITCSS & utility-first",
        "CSS Modules",
        "CSS-in-JS",
        "Atomic / utility CSS (Tailwind)",
        "Design tokens",
        "Naming conventions & scalability",
      ]},
      {"g":"Preprocessors & Tooling","items":[
        "Sass / SCSS (variables, mixins, nesting, partials)",
        "Less & Stylus",
        "PostCSS & plugins",
        "Autoprefixer",
        "Stylelint",
        "CSS minification & purging unused CSS",
      ]},
    ]},

    {"name":"5. JavaScript Language","tag":"javascript","groups":[
      {"g":"Basics","items":[
        "Variables (var, let, const)",
        "Hoisting & temporal dead zone",
        "Data types (primitives & objects)",
        "Type coercion & conversion",
        "Truthy & falsy values",
        "Operators (arithmetic, comparison, logical, bitwise)",
        "Strict vs loose equality (=== vs ==)",
        "Nullish coalescing (??) & optional chaining (?.)",
        "Template literals",
        "Comments & strict mode",
      ]},
      {"g":"Functions","items":[
        "Function declarations vs expressions",
        "Arrow functions & lexical this",
        "Parameters, default & rest parameters",
        "Spread syntax",
        "Closures",
        "IIFE (immediately invoked function expressions)",
        "Higher-order functions",
        "Callbacks",
        "Currying & partial application",
        "Recursion",
        "call, apply, bind",
        "this binding rules",
      ]},
      {"g":"Objects & Data Structures","items":[
        "Object literals & property shorthand",
        "Property descriptors & getters/setters",
        "Computed property names",
        "Destructuring (object & array)",
        "Arrays & array methods (map, filter, reduce, forEach, find)",
        "Iteration methods & immutability patterns",
        "Map, Set, WeakMap, WeakSet",
        "JSON.parse / JSON.stringify",
        "Symbols",
        "Numbers, BigInt & precision",
        "Strings & string methods",
        "Dates & the Temporal proposal",
      ]},
      {"g":"Prototypes & Classes","items":[
        "Prototypal inheritance",
        "Prototype chain",
        "Object.create & Object.assign",
        "Constructor functions",
        "ES6 classes",
        "Class fields & private fields (#)",
        "Static methods & properties",
        "extends & super",
        "Mixins",
        "instanceof & Object.getPrototypeOf",
      ]},
      {"g":"Asynchronous JS","items":[
        "Synchronous vs asynchronous execution",
        "Call stack",
        "Event loop",
        "Microtasks vs macrotasks",
        "Callbacks & callback hell",
        "Promises (then, catch, finally)",
        "Promise.all, allSettled, race, any",
        "async / await",
        "Error handling in async code",
        "setTimeout, setInterval, queueMicrotask",
        "requestAnimationFrame & requestIdleCallback",
        "Generators & iterators",
        "Async iterators & for-await-of",
      ]},
      {"g":"Modules","items":[
        "ES Modules (import / export)",
        "Default vs named exports",
        "Dynamic import()",
        "CommonJS (require / module.exports)",
        "Module scope & tree-shaking",
        "Import maps",
        "Top-level await",
      ]},
      {"g":"Advanced & Runtime","items":[
        "Execution context & scope chain",
        "Garbage collection",
        "Memory leaks & weak references",
        "Tagged templates",
        "Proxy & Reflect",
        "Iterators & iterables protocol",
        "Error objects & custom errors",
        "Regular expressions",
        "Internationalization (Intl API)",
        "Web Workers & worker threads",
        "Structured clone",
        "Event-driven programming",
      ]},
      {"g":"Patterns & Quality","items":[
        "Module pattern & revealing module",
        "Observer / pub-sub pattern",
        "Singleton, factory, strategy patterns",
        "Debounce & throttle",
        "Memoization",
        "Functional programming concepts (pure functions, immutability)",
        "Composition over inheritance",
        "Linting (ESLint) & formatting (Prettier)",
        "Common pitfalls (this, closures in loops, floating point)",
      ]},
    ]},

    {"name":"6. TypeScript","tag":"typescript","groups":[
      {"g":"Fundamentals","items":[
        "Why TypeScript (static typing benefits)",
        "Type annotations & inference",
        "Primitive types & any / unknown / never",
        "Arrays, tuples & enums",
        "Union & intersection types",
        "Literal types & const assertions",
        "Type aliases vs interfaces",
        "Optional & readonly properties",
        "Function types & overloads",
      ]},
      {"g":"Advanced Types","items":[
        "Generics & generic constraints",
        "Utility types (Partial, Pick, Omit, Record, Required)",
        "Mapped types",
        "Conditional types",
        "Template literal types",
        "keyof, typeof, indexed access types",
        "Type guards & narrowing",
        "Discriminated unions",
        "Type predicates & assertion functions",
        "Declaration merging",
      ]},
      {"g":"Tooling & Config","items":[
        "tsconfig.json & compiler options",
        "strict mode flags",
        "Declaration files (.d.ts) & DefinitelyTyped",
        "Module resolution",
        "Type-only imports",
        "Integrating TS with bundlers",
        "ts-node & runtime type checking",
        "Migrating JS to TS",
      ]},
    ]},

    {"name":"7. DOM, BOM & Browser APIs","tag":"dom","groups":[
      {"g":"DOM Manipulation","items":[
        "Document Object Model (DOM) tree",
        "Selecting elements (getElementById, querySelector, querySelectorAll)",
        "Creating & inserting nodes",
        "Modifying attributes & content (textContent, innerHTML, innerText)",
        "classList API",
        "Traversing the DOM (parent, children, siblings)",
        "Removing & replacing nodes",
        "DocumentFragment",
        "Reflow & repaint",
        "Virtual DOM concept",
      ]},
      {"g":"Events","items":[
        "Event listeners (addEventListener / removeEventListener)",
        "Event object & properties",
        "Event bubbling & capturing",
        "Event delegation",
        "preventDefault & stopPropagation",
        "Custom events & dispatchEvent",
        "Passive event listeners",
        "Pointer, touch, mouse & keyboard events",
        "Input & change events",
        "AbortController & AbortSignal",
      ]},
      {"g":"BOM & Window","items":[
        "window object",
        "location & history (History API, pushState)",
        "navigator object",
        "screen & viewport dimensions",
        "Timers (setTimeout / setInterval)",
        "Dialogs (alert, confirm, prompt)",
        "postMessage & cross-window communication",
        "Clipboard API",
      ]},
      {"g":"Fetching Data","items":[
        "XMLHttpRequest (legacy)",
        "Fetch API",
        "Request & Response objects",
        "Headers object",
        "Streaming responses",
        "AbortController for fetch cancellation",
        "Server-Sent Events (EventSource)",
        "WebSocket API",
        "Beacon API",
      ]},
      {"g":"Modern Browser APIs","items":[
        "Intersection Observer",
        "Mutation Observer",
        "Resize Observer",
        "Performance Observer",
        "Geolocation API",
        "Web Storage API",
        "IndexedDB",
        "Web Workers & Service Workers",
        "Notifications & Push API",
        "Web Audio & WebRTC",
        "WebGL & WebGPU",
        "WebAssembly (Wasm)",
        "File & Blob APIs",
        "Drag and Drop API",
        "Fullscreen, Visibility & Battery APIs",
        "Web Share API",
        "Credential Management & WebAuthn",
      ]},
      {"g":"Rendering Internals","items":[
        "Critical rendering path",
        "Parsing HTML & CSSOM construction",
        "Render tree, layout, paint, composite",
        "Reflow vs repaint cost",
        "Layer promotion & compositing",
        "requestAnimationFrame loop",
        "Browser paint & main-thread work",
      ]},
    ]},

    {"name":"8. Frontend Frameworks & Architecture","tag":"frameworks","groups":[
      {"g":"Concepts","items":[
        "Library vs framework",
        "Component-based architecture",
        "Declarative vs imperative UI",
        "Unidirectional data flow",
        "Props & component composition",
        "Reactivity & data binding",
        "Virtual DOM vs incremental DOM vs no-VDOM",
        "Component lifecycle",
        "Hooks / composition model",
        "Single-page applications (SPA)",
        "Multi-page applications (MPA)",
        "Islands architecture",
        "Micro-frontends",
      ]},
      {"g":"React","items":[
        "JSX",
        "Function components vs class components",
        "Props & state",
        "useState, useEffect, useRef",
        "useMemo, useCallback, useReducer",
        "useContext & context API",
        "Custom hooks",
        "Rules of hooks",
        "Reconciliation & keys",
        "Refs & forwardRef",
        "Error boundaries",
        "Suspense & lazy loading",
        "Concurrent features & transitions",
        "Server Components",
        "React 19 actions & use()",
      ]},
      {"g":"Vue","items":[
        "Templates & directives (v-if, v-for, v-model)",
        "Reactivity system (ref, reactive)",
        "Composition API vs Options API",
        "Computed & watchers",
        "Components & props/emits",
        "Slots & scoped slots",
        "Lifecycle hooks",
        "Provide / inject",
        "Single-file components (.vue)",
      ]},
      {"g":"Angular","items":[
        "Modules & standalone components",
        "Templates & data binding",
        "Directives & pipes",
        "Dependency injection",
        "Services",
        "RxJS & observables",
        "Signals",
        "Change detection",
        "Routing & guards",
      ]},
      {"g":"Other Frameworks","items":[
        "Svelte & compile-time reactivity",
        "SvelteKit",
        "SolidJS (fine-grained reactivity)",
        "Qwik & resumability",
        "Preact",
        "Lit & web components",
        "Alpine.js & HTMX",
        "Astro",
      ]},
      {"g":"Meta-Frameworks","items":[
        "Next.js",
        "Nuxt",
        "Remix / React Router framework",
        "SvelteKit",
        "App router vs pages router patterns",
        "File-based routing",
        "Data loading conventions",
        "Server actions / form actions",
      ]},
      {"g":"Routing","items":[
        "Client-side routing",
        "History API & hash routing",
        "Nested & dynamic routes",
        "Route params & query strings",
        "Route guards & protected routes",
        "Lazy-loaded routes & code splitting",
        "Scroll restoration",
      ]},
    ]},

    {"name":"9. State Management","tag":"state","groups":[
      {"g":"Concepts","items":[
        "Local vs global state",
        "UI state vs server state vs URL state",
        "Derived state",
        "State colocation",
        "Prop drilling & lifting state up",
        "Immutability in state",
        "Single source of truth",
        "Flux architecture",
      ]},
      {"g":"Client State Libraries","items":[
        "Context API patterns",
        "Redux & Redux Toolkit",
        "Reducers, actions & middleware",
        "Zustand",
        "Jotai & atomic state",
        "MobX & observables",
        "Recoil",
        "Pinia (Vue)",
        "XState & state machines",
        "Signals as state primitive",
      ]},
      {"g":"Server State","items":[
        "Server state vs client state distinction",
        "TanStack Query (React Query)",
        "SWR",
        "Caching, invalidation & revalidation",
        "Optimistic updates",
        "Mutations & rollback",
        "Pagination & infinite queries",
        "Background refetching",
        "RTK Query",
      ]},
    ]},

    {"name":"10. Build Tools & Tooling","tag":"build","groups":[
      {"g":"Module Bundlers","items":[
        "What a bundler does",
        "Webpack (entry, output, loaders, plugins)",
        "Vite & native ESM dev server",
        "Rollup",
        "esbuild",
        "Parcel",
        "Turbopack",
        "Rspack",
        "Code splitting & dynamic imports",
        "Tree shaking & dead code elimination",
        "Source maps",
        "Hot Module Replacement (HMR)",
        "Asset handling (images, fonts, CSS)",
      ]},
      {"g":"Transpilers & Compilers","items":[
        "Babel & presets/plugins",
        "SWC",
        "TypeScript compiler (tsc)",
        "PostCSS pipeline",
        "Polyfills & core-js",
        "browserslist & targeting",
      ]},
      {"g":"Package Management","items":[
        "npm & package.json",
        "Semantic versioning (semver)",
        "Lockfiles (package-lock, yarn.lock, pnpm-lock)",
        "Dependencies vs devDependencies vs peerDependencies",
        "yarn & pnpm",
        "Workspaces & monorepos",
        "npm scripts",
        "npx & package execution",
        "Publishing packages",
        "Dependency auditing & supply-chain risk",
      ]},
      {"g":"Monorepo & Workflow","items":[
        "Monorepo tooling (Nx, Turborepo, Lerna)",
        "Task caching & affected builds",
        "Git hooks (Husky, lint-staged)",
        "Commit conventions & changelogs",
        "Linters & formatters in CI",
        "Editor config & DX tooling",
      ]},
    ]},

    {"name":"11. Backend Web Development","tag":"backend","groups":[
      {"g":"Server Fundamentals","items":[
        "What a web server does",
        "Application server vs web server",
        "Request routing",
        "Middleware pipeline",
        "Controllers & handlers",
        "Request parsing & body handling",
        "Response generation & serialization",
        "Templating / server-side rendering",
        "Static file serving",
        "Environment configuration & secrets",
        "Logging & error handling",
        "Graceful shutdown",
      ]},
      {"g":"Runtimes & Languages","items":[
        "Node.js event loop & non-blocking I/O",
        "Deno & Bun",
        "JVM (Java/Kotlin) for web",
        "Python (Django/Flask/FastAPI)",
        "Go, Rust & PHP for web",
        "Serverless functions / FaaS",
        "Edge runtimes & edge functions",
      ]},
      {"g":"Backend Frameworks","items":[
        "Express & Koa",
        "Fastify, NestJS",
        "Spring Boot / Spring MVC / WebFlux",
        "Django & FastAPI",
        "Concurrency models (threads vs async)",
        "Connection pooling",
      ]},
      {"g":"Concerns","items":[
        "Request validation",
        "Rate limiting & throttling",
        "Pagination, filtering, sorting",
        "Background jobs & queues",
        "Scheduled tasks / cron",
        "File uploads & storage",
        "Email & notifications",
        "Idempotency keys",
        "Health checks & readiness probes",
      ]},
    ]},

    {"name":"12. APIs & Communication","tag":"apis","groups":[
      {"g":"REST","items":[
        "REST principles & constraints",
        "Resources & URIs",
        "HTTP methods mapped to CRUD",
        "Statelessness & cacheability",
        "Richardson Maturity Model",
        "HATEOAS",
        "Status codes for APIs",
        "Versioning strategies (URI, header, media type)",
        "Pagination (offset, cursor)",
        "Filtering, sorting, sparse fieldsets",
        "Content negotiation",
        "Error response formats (Problem Details RFC 7807)",
        "Idempotency",
        "API design best practices",
      ]},
      {"g":"GraphQL","items":[
        "Schema & type system",
        "Queries, mutations, subscriptions",
        "Resolvers",
        "Schema definition language (SDL)",
        "N+1 problem & DataLoader",
        "Fragments & directives",
        "Introspection",
        "Federation & schema stitching",
        "Caching in GraphQL",
        "GraphQL vs REST trade-offs",
      ]},
      {"g":"RPC & Streaming","items":[
        "RPC concept",
        "gRPC & Protocol Buffers",
        "gRPC-Web",
        "tRPC (type-safe RPC)",
        "JSON-RPC",
        "WebSockets (full-duplex)",
        "Server-Sent Events (SSE)",
        "Long polling & short polling",
        "WebTransport",
        "Real-time architecture patterns",
      ]},
      {"g":"API Tooling & Docs","items":[
        "OpenAPI / Swagger",
        "API documentation generation",
        "Postman & Insomnia",
        "Mock servers & contract testing",
        "API gateways",
        "Webhooks",
        "API keys vs OAuth for APIs",
        "Versioning & deprecation policy",
      ]},
    ]},

    {"name":"13. Data & Persistence","tag":"data","groups":[
      {"g":"Databases","items":[
        "Relational databases (SQL)",
        "NoSQL (document, key-value, column, graph)",
        "ACID vs BASE",
        "Normalization & denormalization",
        "Indexes & query optimization",
        "Transactions & isolation levels",
        "Primary & foreign keys",
        "Joins & relationships",
        "Schema design & migrations",
        "Connection pooling",
      ]},
      {"g":"Data Access","items":[
        "ORMs & query builders (Prisma, Sequelize, TypeORM, Drizzle)",
        "Raw SQL vs ORM trade-offs",
        "JPA / Hibernate (JVM)",
        "Repository pattern",
        "Data mapper vs active record",
        "N+1 query problem",
        "Caching layers (Redis, Memcached)",
        "Read replicas & sharding basics",
      ]},
      {"g":"Client-Side Data","items":[
        "Cookies",
        "localStorage & sessionStorage",
        "IndexedDB",
        "Cache Storage API",
        "Offline data sync",
        "Optimistic UI & conflict resolution",
      ]},
    ]},

    {"name":"14. Authentication & Authorization","tag":"auth","groups":[
      {"g":"Authentication","items":[
        "Authentication vs authorization",
        "Password-based auth & hashing (bcrypt, argon2)",
        "Salting & peppering",
        "Session-based authentication",
        "Token-based authentication",
        "JSON Web Tokens (JWT) structure & claims",
        "Access tokens vs refresh tokens",
        "Multi-factor authentication (MFA/2FA)",
        "TOTP & WebAuthn / passkeys",
        "Magic links & passwordless",
        "Single Sign-On (SSO)",
      ]},
      {"g":"Authorization & Protocols","items":[
        "OAuth 2.0 flows (authorization code, PKCE, client credentials)",
        "OpenID Connect (OIDC)",
        "SAML",
        "Role-based access control (RBAC)",
        "Attribute-based access control (ABAC)",
        "Scopes & permissions",
        "Access control lists (ACL)",
        "Token storage (cookie vs localStorage trade-offs)",
        "Refresh token rotation",
        "Logout & token revocation",
      ]},
    ]},

    {"name":"15. Web Security","tag":"security","groups":[
      {"g":"Common Vulnerabilities","items":[
        "OWASP Top 10 overview",
        "Cross-Site Scripting (XSS) — stored, reflected, DOM",
        "Cross-Site Request Forgery (CSRF)",
        "SQL injection",
        "Command & code injection",
        "Server-Side Request Forgery (SSRF)",
        "Insecure direct object references (IDOR)",
        "Clickjacking",
        "Open redirects",
        "Security misconfiguration",
        "Sensitive data exposure",
        "Broken access control",
      ]},
      {"g":"Defenses","items":[
        "Input validation & output encoding",
        "Content Security Policy (CSP)",
        "Security headers (HSTS, X-Frame-Options, X-Content-Type-Options)",
        "SameSite cookies & CSRF tokens",
        "Subresource Integrity (SRI)",
        "HTTPS everywhere & TLS",
        "CORS configuration",
        "Sanitizing HTML (DOMPurify)",
        "Escaping in templates",
        "Rate limiting & brute-force protection",
        "Secrets management",
        "Dependency / supply-chain security",
        "Trusted Types",
      ]},
    ]},

    {"name":"16. Performance & Optimization","tag":"performance","groups":[
      {"g":"Loading Performance","items":[
        "Critical rendering path optimization",
        "Minification & compression (gzip, brotli)",
        "Code splitting & lazy loading",
        "Tree shaking",
        "Resource hints (preload, prefetch, preconnect, dns-prefetch)",
        "Image optimization (formats: WebP, AVIF)",
        "Responsive images & srcset",
        "Font optimization & subsetting",
        "Caching strategies",
        "CDN usage",
        "Reducing render-blocking resources",
        "HTTP/2 & HTTP/3 benefits",
      ]},
      {"g":"Runtime Performance","items":[
        "Minimizing reflow & repaint",
        "Debouncing & throttling",
        "Virtualization / windowing for long lists",
        "Web Workers for offloading",
        "Memoization & avoiding re-renders",
        "Memory leak prevention",
        "Avoiding layout thrashing",
        "Efficient animations (transform/opacity)",
      ]},
      {"g":"Measurement","items":[
        "Core Web Vitals (LCP, INP, CLS)",
        "First Contentful Paint & Time to Interactive",
        "Lighthouse audits",
        "Chrome DevTools Performance panel",
        "WebPageTest",
        "Real User Monitoring (RUM) vs synthetic",
        "Performance budgets",
        "Bundle analysis",
      ]},
    ]},

    {"name":"17. Accessibility (a11y)","tag":"a11y","groups":[
      {"g":"Foundations","items":[
        "Why accessibility matters",
        "WCAG principles (Perceivable, Operable, Understandable, Robust)",
        "WCAG conformance levels (A, AA, AAA)",
        "Disabilities & assistive technologies",
        "Screen readers (NVDA, JAWS, VoiceOver)",
        "Keyboard-only navigation",
      ]},
      {"g":"Implementation","items":[
        "Semantic HTML for accessibility",
        "ARIA roles, states & properties",
        "ARIA landmarks",
        "Accessible names & descriptions",
        "Focus management & focus traps",
        "tabindex usage",
        "Skip links",
        "Color contrast",
        "Accessible forms & error messaging",
        "Alt text best practices",
        "Live regions (aria-live)",
        "Reduced motion preferences",
      ]},
      {"g":"Testing","items":[
        "axe & accessibility linters",
        "Lighthouse a11y audit",
        "Manual screen reader testing",
        "Keyboard testing",
        "Automated vs manual a11y testing",
      ]},
    ]},

    {"name":"18. SEO & Discoverability","tag":"seo","groups":[
      {"g":"Technical SEO","items":[
        "How search engines crawl & index",
        "robots.txt",
        "XML sitemaps",
        "Canonical URLs",
        "Meta tags (title, description)",
        "Structured data & schema.org (JSON-LD)",
        "Open Graph & social cards",
        "Semantic HTML & headings for SEO",
        "Mobile-friendliness & Core Web Vitals",
        "SSR/SSG for crawlability",
        "Pagination & rel=next/prev",
        "Internationalization (hreflang)",
        "URL structure & redirects (301 vs 302)",
      ]},
    ]},

    {"name":"19. Rendering Strategies","tag":"rendering","groups":[
      {"g":"Approaches","items":[
        "Client-Side Rendering (CSR)",
        "Server-Side Rendering (SSR)",
        "Static Site Generation (SSG)",
        "Incremental Static Regeneration (ISR)",
        "Hydration & partial hydration",
        "Streaming SSR",
        "Resumability (Qwik)",
        "Islands architecture",
        "Edge rendering",
        "Progressive enhancement vs graceful degradation",
        "Trade-offs (SEO, TTFB, interactivity, complexity)",
      ]},
    ]},

    {"name":"20. Progressive Web Apps","tag":"pwa","groups":[
      {"g":"PWA","items":[
        "What makes an app a PWA",
        "Web App Manifest",
        "Service Workers lifecycle",
        "Caching strategies (cache-first, network-first, stale-while-revalidate)",
        "Offline support",
        "Background sync",
        "Push notifications",
        "Add to home screen / installability",
        "App shell architecture",
        "Workbox",
        "Capabilities & limitations vs native",
      ]},
    ]},

    {"name":"21. Testing","tag":"testing","groups":[
      {"g":"Types","items":[
        "Testing pyramid",
        "Unit testing",
        "Integration testing",
        "End-to-end (E2E) testing",
        "Component testing",
        "Visual regression testing",
        "Accessibility testing",
        "Performance testing",
        "Contract testing",
        "Snapshot testing",
      ]},
      {"g":"Tools & Practices","items":[
        "Jest & Vitest",
        "Testing Library (DOM/React/Vue)",
        "Cypress & Playwright",
        "Mocking & stubbing",
        "Test doubles (mocks, spies, fakes)",
        "Code coverage",
        "Test-driven development (TDD)",
        "Arrange-Act-Assert",
        "Flaky tests & determinism",
        "CI test integration",
      ]},
    ]},

    {"name":"22. DevOps, Deployment & Hosting","tag":"devops","groups":[
      {"g":"Version Control & CI/CD","items":[
        "Git fundamentals & branching strategies",
        "Pull requests & code review",
        "Continuous Integration (CI)",
        "Continuous Delivery / Deployment (CD)",
        "Build pipelines (GitHub Actions, GitLab CI)",
        "Automated testing in pipelines",
        "Environment variables & config per env",
        "Feature flags",
      ]},
      {"g":"Hosting & Infrastructure","items":[
        "Static hosting (Netlify, Vercel, GitHub Pages, Cloudflare Pages)",
        "Serverless & edge functions",
        "Container deployment (Docker)",
        "Orchestration (Kubernetes) overview",
        "Reverse proxies (Nginx)",
        "Load balancing & autoscaling",
        "CDN configuration",
        "DNS & domain setup",
        "TLS certificates (Let's Encrypt)",
        "Blue-green & canary deployments",
        "Rollbacks",
      ]},
      {"g":"Observability","items":[
        "Logging",
        "Metrics & dashboards",
        "Distributed tracing",
        "Error tracking (Sentry)",
        "Uptime monitoring & alerting",
        "Real User Monitoring",
      ]},
    ]},

    {"name":"23. Web Standards & Compatibility","tag":"standards","groups":[
      {"g":"Standards & Browsers","items":[
        "W3C, WHATWG & TC39",
        "ECMAScript proposal process (stages)",
        "How standards become features",
        "Browser engines (Blink, Gecko, WebKit)",
        "Rendering & JS engines (V8, SpiderMonkey, JavaScriptCore)",
        "Cross-browser compatibility",
        "Feature detection vs browser sniffing",
        "Progressive enhancement",
        "Polyfills & transpilation",
        "Can I Use & Baseline",
        "Vendor prefixes",
        "Graceful degradation",
        "Accessibility & internationalization standards",
      ]},
    ]},

    {"name":"24. Spring — How Spring Helps","tag":"spring","groups":[
      {"g":"Serving the Web Layer","items":[
        "Spring MVC for server-rendered & REST endpoints",
        "@Controller vs @RestController",
        "Request mapping (@GetMapping/@PostMapping etc.)",
        "Path variables, request params & request bodies",
        "Content negotiation & message converters (Jackson)",
        "Thymeleaf server-side templating",
        "Static resource handling & versioned resource URLs",
        "Spring WebFlux for reactive, non-blocking web",
        "WebSocket & STOMP support",
        "Server-Sent Events with reactive types",
      ]},
      {"g":"APIs & Communication","items":[
        "Building REST APIs with Spring Boot",
        "Spring HATEOAS for hypermedia",
        "Problem Details (RFC 7807) support",
        "OpenAPI/Swagger via springdoc",
        "Spring for GraphQL",
        "gRPC integration",
        "RestClient / WebClient / RestTemplate for outbound calls",
        "Spring Cloud OpenFeign declarative clients",
        "API versioning patterns",
      ]},
      {"g":"Data, Security & Ops","items":[
        "Spring Data JPA repositories",
        "Spring Data REST auto-exposed endpoints",
        "Transaction management (@Transactional)",
        "Spring Security for authn/authz",
        "OAuth2 / OIDC resource server & client",
        "JWT support & method security",
        "CSRF & security headers via Spring Security",
        "CORS configuration",
        "Bean validation (Jakarta Validation)",
        "Spring Boot Actuator (health, metrics, info)",
        "Micrometer metrics & distributed tracing",
        "Centralized exception handling (@ControllerAdvice)",
        "Profiles & externalized configuration",
        "Spring Boot DevTools & live reload",
      ]},
    ]},

  ],
}

PROJECTS = [WEBDEV]
