# -*- coding: utf-8 -*-
"""Spring AI, gRPC, GraphQL, HATEOAS, REST Docs, Web Services."""

AI = {
  "file":"spring-ai.html","title":"Spring AI","logo":"AI","cat":"Web & API",
  "subtitle":"Spring-idiomatic AI engineering — models, prompts, RAG, tools, agents.",
  "sections":[
    {"name":"1. Concepts & Models","tag":"core","groups":[
      {"g":"Foundations","items":[
        "Spring AI goals & portability across providers",
        "AI concepts (models, prompts, tokens, embeddings)",
        "Supported model providers overview",
        "Spring Boot starters for AI",
        "ChatClient fluent API",
        "ChatModel abstraction",
        "Prompt & PromptTemplate",
        "Messages (System/User/Assistant/Tool)",
        "ChatResponse & generations",
        "ChatOptions (temperature, max tokens, etc.)",
        "Streaming responses (Flux)",
        "Default system prompts & advisors defaults",
      ]},
      {"g":"Model Providers","items":[
        "OpenAI chat / image / audio / embeddings",
        "Anthropic Claude chat",
        "Azure OpenAI",
        "Amazon Bedrock (Converse & models)",
        "Google VertexAI Gemini",
        "Mistral AI",
        "Ollama (local models)",
        "Hugging Face",
        "MiniMax / ZhiPuAI / Moonshot / others",
        "Model configuration & properties",
      ]},
    ]},
    {"name":"2. Prompts, Output & Multimodality","tag":"prompt","groups":[
      {"g":"Prompts & Output","items":[
        "Prompt engineering with templates",
        "Template rendering (StringTemplate)",
        "Structured output converters (Bean/Map/List)",
        "Output parsing & format instructions",
        "Multimodality (images, audio inputs)",
        "Image generation (ImageModel)",
        "Audio transcription (speech-to-text)",
        "Text-to-speech",
        "Embeddings (EmbeddingModel)",
        "Moderation API",
      ]},
    ]},
    {"name":"3. RAG, Vector Stores & Memory","tag":"rag","groups":[
      {"g":"RAG & Vectors","items":[
        "Retrieval Augmented Generation (RAG) concept",
        "Document & DocumentReader (PDF, Tika, JSON, text, Markdown)",
        "ETL pipeline (read, transform, write)",
        "Document transformers (splitters, metadata enrichers)",
        "Token text splitter",
        "EmbeddingModel for documents",
        "VectorStore abstraction",
        "Vector store implementations (PgVector, Redis, Chroma, Milvus, Pinecone, Weaviate, Qdrant, etc.)",
        "Similarity search & filters",
        "Metadata filtering (filter expression DSL)",
        "RAG advisors (QuestionAnswerAdvisor, RetrievalAugmentationAdvisor)",
        "Modular RAG architecture",
      ]},
      {"g":"Memory & Advisors","items":[
        "Chat memory (ChatMemory)",
        "Memory repositories (in-memory, JDBC, Cassandra, Neo4j)",
        "Advisors API (request/response interception)",
        "MessageChatMemoryAdvisor / PromptChatMemoryAdvisor",
        "SafeGuardAdvisor",
        "Logging advisor",
      ]},
    ]},
    {"name":"4. Tools, MCP & Agents","tag":"agents","groups":[
      {"g":"Tool Calling & MCP","items":[
        "Tool calling (function calling) concept",
        "@Tool annotation & ToolCallback",
        "Method & function tools",
        "Tool context & parameters",
        "Tool execution lifecycle",
        "Model Context Protocol (MCP) client",
        "MCP server support",
        "MCP transports (stdio, SSE)",
        "Observability (metrics & tracing) for AI",
        "Agents & workflows patterns",
        "Evaluation (Evaluator, relevancy/fact-checking)",
        "Testing AI components",
      ]},
    ]},
  ],
}

GRPC = {
  "file":"spring-grpc.html","title":"Spring gRPC","logo":"G","cat":"Web & API",
  "subtitle":"Develop gRPC applications with Spring Boot conventions.",
  "sections":[
    {"name":"1. gRPC with Spring","tag":"core","groups":[
      {"g":"Fundamentals","items":[
        "gRPC concepts (protobuf, HTTP/2, service definitions)",
        "Protocol Buffers & .proto files",
        "Code generation (protobuf-maven/gradle plugin)",
        "Spring gRPC project overview",
        "Spring Boot starter for gRPC",
        "gRPC server auto-configuration",
        "Implementing a service (BindableService / base class)",
        "Server interceptors",
        "Server reflection & health service",
        "Server properties (port, security)",
        "Exception handling (@GrpcExceptionHandler)",
      ]},
      {"g":"Client & Advanced","items":[
        "gRPC client (ManagedChannel)",
        "Channel configuration & naming",
        "Stub injection (@GrpcClient style)",
        "Client interceptors",
        "Unary / server-streaming / client-streaming / bidirectional",
        "Deadlines & cancellation",
        "TLS / security",
        "Observability (metrics, tracing)",
        "In-process server for testing",
        "gRPC over Servlet / reactive considerations",
      ]},
    ]},
  ],
}

GRAPHQL = {
  "file":"spring-for-graphql.html","title":"Spring for GraphQL","logo":"Gq","cat":"Web & API",
  "subtitle":"GraphQL support on top of GraphQL Java, integrated with Spring.",
  "sections":[
    {"name":"1. Core & Transports","tag":"core","groups":[
      {"g":"Foundations","items":[
        "GraphQL concepts (schema, queries, mutations, subscriptions)",
        "GraphQL Java engine integration",
        "Schema-first development (.graphqls files)",
        "RuntimeWiring & wiring configurers",
        "GraphQlSource",
        "ExecutionGraphQlService",
        "Spring Boot GraphQL starter",
      ]},
      {"g":"Transports","items":[
        "HTTP transport (Spring MVC)",
        "HTTP transport (WebFlux)",
        "WebSocket transport (subscriptions)",
        "RSocket transport",
        "Server-Sent Events (SSE)",
        "GraphiQL UI",
        "Schema printing / introspection endpoint",
        "CORS configuration",
      ]},
    ]},
    {"name":"2. Data Fetching & Annotations","tag":"data","groups":[
      {"g":"Controllers","items":[
        "Annotated controllers (@Controller for GraphQL)",
        "@QueryMapping / @MutationMapping / @SubscriptionMapping",
        "@SchemaMapping (field & type)",
        "@BatchMapping (batch loading)",
        "Method arguments (@Argument, @Argument with binding)",
        "@ProjectedPayload / input projections",
        "DataLoader & N+1 problem",
        "Context propagation (GraphQLContext)",
        "@ContextValue / @LocalContextValue",
        "Return types (Mono/Flux, CompletableFuture, Callable)",
        "Exception handling (@GraphQlExceptionHandler / DataFetcherExceptionResolver)",
        "Errors & error types (GraphQLError)",
        "Validation",
      ]},
      {"g":"Data & Security Integration","items":[
        "Spring Data integration (auto-registered repositories)",
        "Querydsl & Query by Example data fetchers",
        "Pagination (Connection model / cursor)",
        "Scroll & keyset pagination",
        "Sorting",
        "Spring Security integration (@PreAuthorize on controllers)",
        "Spring Security context propagation",
        "Federation (Apollo) support",
      ]},
    ]},
    {"name":"3. Client & Testing","tag":"client","groups":[
      {"g":"Client & Testing","items":[
        "GraphQlClient (HTTP / WebSocket / RSocket)",
        "Retrieving documents & fields",
        "Document source loading",
        "Testing with GraphQlTester",
        "HttpGraphQlTester / WebGraphQlTester",
        "ExecutionGraphQlServiceTester",
        "Subscription testing",
        "Observability (metrics & tracing)",
      ]},
    ]},
  ],
}

HATEOAS = {
  "file":"spring-hateoas.html","title":"Spring HATEOAS","logo":"H","cat":"Web & API",
  "subtitle":"Create hypermedia-driven REST representations following HATEOAS.",
  "sections":[
    {"name":"1. Representation Model","tag":"core","groups":[
      {"g":"Models & Links","items":[
        "HATEOAS / hypermedia REST concept",
        "RepresentationModel",
        "EntityModel",
        "CollectionModel",
        "PagedModel",
        "Link & link relations (IanaLinkRelations)",
        "LinkRelation",
        "Affordances",
        "RepresentationModelAssembler",
        "RepresentationModelAssemblerSupport",
        "SimpleRepresentationModelAssembler",
      ]},
      {"g":"Link Building","items":[
        "WebMvcLinkBuilder (linkTo / methodOn)",
        "WebFluxLinkBuilder",
        "Building links to controllers",
        "Link affordances (afford)",
        "Templated links & URI templates",
        "Adding links to models",
      ]},
    ]},
    {"name":"2. Media Types & Config","tag":"media","groups":[
      {"g":"Hypermedia Formats","items":[
        "HAL media type",
        "HAL-FORMS",
        "Collection+JSON",
        "UBER",
        "ALPS",
        "Configuring media types (@EnableHypermediaSupport)",
        "Link relation provider",
        "CurieProvider (documentation curies)",
        "Custom media type & link discoverer",
      ]},
      {"g":"Clients & Config","items":[
        "Client-side support (Traverson)",
        "LinkDiscoverer",
        "RestTemplate / WebClient hypermedia config",
        "Configuration & customization",
        "Spring Boot HATEOAS auto-config",
      ]},
    ]},
  ],
}

REST_DOCS = {
  "file":"spring-rest-docs.html","title":"Spring REST Docs","logo":"R","cat":"Web & API",
  "subtitle":"Test-driven documentation for RESTful services using Asciidoctor & snippets.",
  "sections":[
    {"name":"1. Getting Started & Snippets","tag":"core","groups":[
      {"g":"Setup","items":[
        "Documentation philosophy (test-driven docs)",
        "Asciidoctor vs Markdown",
        "Build configuration (Maven / Gradle)",
        "Packaging documentation",
        "Generating snippets via tests",
        "MockMvc integration",
        "WebTestClient integration",
        "REST Assured integration",
        "@AutoConfigureRestDocs (Spring Boot)",
      ]},
      {"g":"Documenting Requests/Responses","items":[
        "document() & snippets",
        "Request/response fields (fieldWithPath)",
        "Path parameters",
        "Query/request parameters",
        "Request/response headers",
        "Request parts (multipart)",
        "Hypermedia links (links())",
        "Constraints documentation",
        "Subsection / payload subsections",
        "Default snippets (curl, http-request, http-response, httpie)",
        "Reusing snippets (preprocessors)",
        "Request/response preprocessing (prettyPrint, maskLinks, etc.)",
      ]},
    ]},
    {"name":"2. Customization & Advanced","tag":"adv","groups":[
      {"g":"Advanced","items":[
        "Custom snippet templates (Mustache)",
        "Custom snippets",
        "Documenting constraints from Bean Validation",
        "Operation & operation attributes",
        "Configuring host/scheme/port (URI customization)",
        "Snippets in AsciiDoc (operation macro, include)",
        "Generating a single document",
        "Working with cookies",
        "Testing with REST Assured details",
        "Contract testing relationship (Spring Cloud Contract)",
      ]},
    ]},
  ],
}

WEB_SERVICES = {
  "file":"spring-web-services.html","title":"Spring Web Services","logo":"W","cat":"Web & API",
  "subtitle":"Contract-first SOAP web services with Spring.",
  "sections":[
    {"name":"1. Server-side (contract-first)","tag":"server","groups":[
      {"g":"Concepts & Endpoints","items":[
        "Contract-first vs contract-last",
        "Why contract-first SOAP",
        "MessageDispatcher & MessageDispatcherServlet",
        "Transports (HTTP, JMS, email, XMPP)",
        "WebServiceMessage & SoapMessage",
        "Endpoint mappings (PayloadRootAnnotationMethodEndpointMapping)",
        "@Endpoint / @PayloadRoot / @RequestPayload / @ResponsePayload",
        "@SoapAction mapping",
        "Endpoint interceptors",
        "Payload logging interceptors",
        "Handling XML with marshalling (JAXB) & XPath",
        "@XPathParam",
      ]},
      {"g":"WSDL & XSD","items":[
        "Exposing a WSDL (DefaultWsdl11Definition)",
        "Generating WSDL from XSD",
        "XSD-based schema & validation",
        "CommonsXsdSchemaCollection",
        "Message validation interceptor (PayloadValidatingInterceptor)",
        "WS-Addressing (@Action, AnnotationActionEndpointMapping)",
      ]},
    ]},
    {"name":"2. Client & Security","tag":"client","groups":[
      {"g":"Client","items":[
        "WebServiceTemplate",
        "Sending & receiving (marshalSendAndReceive)",
        "WebServiceMessageCallback",
        "Client-side interceptors",
        "Fault & exception handling (FaultMessageResolver)",
        "URI & message senders (HTTP component)",
      ]},
      {"g":"Security","items":[
        "WS-Security (Wss4jSecurityInterceptor)",
        "Authentication (UsernameToken)",
        "Digital signatures & encryption",
        "XwsSecurityInterceptor (legacy)",
        "Securing with Spring Security",
        "Testing (server-side & client-side test support)",
      ]},
    ]},
  ],
}

PROJECTS = [AI, GRPC, GRAPHQL, HATEOAS, REST_DOCS, WEB_SERVICES]
