# -*- coding: utf-8 -*-
"""Spring Security, Authorization Server, Session, LDAP."""

SECURITY = {
  "file":"spring-security.html","title":"Spring Security","logo":"S","cat":"Security",
  "subtitle":"Authentication, authorization, and protection against common attacks.",
  "sections":[
    {"name":"1. Architecture & Fundamentals","tag":"core","groups":[
      {"g":"Concepts","items":[
        "What Spring Security is & its goals",
        "Authentication vs authorization",
        "Servlet vs reactive (WebFlux) support",
        "Filters & the FilterChainProxy / DelegatingFilterProxy",
        "SecurityFilterChain",
        "Security filter ordering (full chain)",
        "SecurityContext & SecurityContextHolder",
        "SecurityContextHolderStrategy",
        "Authentication object & Principal",
        "GrantedAuthority",
        "AuthenticationManager / ProviderManager",
        "AuthenticationProvider",
        "AuthenticationEntryPoint",
        "AbstractAuthenticationProcessingFilter",
        "Handling security exceptions (ExceptionTranslationFilter)",
        "SecurityContextRepository / persistence",
      ]},
      {"g":"Configuration","items":[
        "Java config (@EnableWebSecurity)",
        "SecurityFilterChain bean (lambda DSL)",
        "HttpSecurity DSL",
        "Multiple security filter chains",
        "WebSecurityCustomizer (ignoring requests)",
        "@EnableMethodSecurity",
        "Migrating from WebSecurityConfigurerAdapter (deprecated)",
        "Default security (auto-config) behavior",
      ]},
    ]},
    {"name":"2. Authentication","tag":"authn","groups":[
      {"g":"Mechanisms","items":[
        "Username/password authentication",
        "Form login",
        "HTTP Basic authentication",
        "HTTP Digest (legacy)",
        "Remember-me authentication (token & persistent)",
        "Anonymous authentication",
        "Pre-authentication scenarios (X.509, SiteMinder, J2EE)",
        "Run-as authentication replacement",
        "Logout handling",
        "Concurrent session control",
        "Session management & fixation protection",
        "Saved requests & redirect after login",
        "One-Time Token login",
        "Passkeys / WebAuthn",
      ]},
      {"g":"Password & User Storage","items":[
        "PasswordEncoder (BCrypt, Argon2, SCrypt, PBKDF2, delegating)",
        "DelegatingPasswordEncoder & {id} format",
        "Password storage history & upgrades",
        "UserDetails & UserDetailsService",
        "InMemoryUserDetailsManager",
        "JdbcUserDetailsManager",
        "UserDetailsPasswordService (password upgrade)",
        "DaoAuthenticationProvider",
        "AuthenticationManagerBuilder",
        "Custom AuthenticationProvider",
        "Account status (locked, expired, disabled)",
        "Compromised password checking (HaveIBeenPwned)",
      ]},
      {"g":"Events & Details","items":[
        "Authentication events (success/failure listeners)",
        "AuthenticationDetailsSource",
        "Credentials erasure",
        "Custom AuthenticationSuccessHandler/FailureHandler",
      ]},
    ]},
    {"name":"3. Authorization","tag":"authz","groups":[
      {"g":"Request Authorization","items":[
        "AuthorizationManager",
        "authorizeHttpRequests DSL",
        "Request matchers (Ant, MVC, regex, path)",
        "Authorities & roles (hasRole, hasAuthority, hasAnyRole)",
        "Access expressions & WebExpressionAuthorizationManager",
        "AccessDecisionManager / Voter (legacy)",
        "Secured object & ConfigAttribute (legacy)",
        "Hierarchical roles (RoleHierarchy)",
        "Authorization events (AuthorizationDeniedEvent/GrantedEvent)",
      ]},
      {"g":"Method Security","items":[
        "@PreAuthorize / @PostAuthorize",
        "@PreFilter / @PostFilter",
        "@Secured (legacy)",
        "JSR-250 (@RolesAllowed, @PermitAll, @DenyAll)",
        "Method security SpEL expressions",
        "Custom security expressions (MethodSecurityExpressionHandler)",
        "AuthorizationManager for methods",
        "@AuthenticationPrincipal",
        "Meta-annotations for method security",
        "Securing domain objects (ACLs)",
        "ACL model (Acl, Sid, Permission, AclService)",
      ]},
    ]},
    {"name":"4. Protection Against Exploits","tag":"exploits","groups":[
      {"g":"Common Protections","items":[
        "CSRF protection (CsrfToken, CsrfTokenRepository)",
        "CSRF with SPA / cookie-based token",
        "Security HTTP response headers (HSTS, X-Frame-Options, CSP, etc.)",
        "Content Security Policy",
        "Referrer Policy / Feature Policy / Permissions Policy",
        "Clickjacking protection (frame options)",
        "HTTP Strict Transport Security",
        "Cache control headers",
        "Content-Type sniffing protection",
        "CORS support (cors DSL & CorsConfigurationSource)",
        "HTTP requirements / channel security (requiresChannel HTTPS)",
        "HttpFirewall & StrictHttpFirewall",
        "Encoding / Firewall request validation",
      ]},
    ]},
    {"name":"5. OAuth2 & OpenID Connect","tag":"oauth2","groups":[
      {"g":"OAuth2 Login & Client","items":[
        "OAuth2 Login (social login)",
        "ClientRegistration & ClientRegistrationRepository",
        "Authorization Code grant flow",
        "OAuth2AuthorizedClient & repository/service",
        "OAuth2 client (WebClient/RestClient integration)",
        "Authorized client manager & providers",
        "Refresh token / client credentials / etc. grants",
        "OpenID Connect 1.0 login",
        "OIDC user info & ID token",
        "OIDC logout (RP-initiated)",
        "Custom user types (OAuth2User/OidcUser)",
      ]},
      {"g":"Resource Server","items":[
        "OAuth2 Resource Server",
        "JWT-based (bearer token) authentication",
        "JwtDecoder & JWK set",
        "Opaque token introspection",
        "Validating audience/issuer/claims",
        "Mapping authorities from claims (JwtAuthenticationConverter)",
        "Multi-tenancy (multiple issuers)",
        "Bearer token resolution",
      ]},
    ]},
    {"name":"6. SAML2 & LDAP & Integrations","tag":"integ","groups":[
      {"g":"SAML2 / LDAP","items":[
        "SAML2 login (service provider)",
        "RelyingPartyRegistration",
        "SAML2 logout",
        "Asserting party metadata",
        "LDAP authentication (BindAuthenticator)",
        "LDAP authorities population",
        "Embedded LDAP server for testing",
        "Active Directory authentication",
      ]},
      {"g":"Reactive & Other","items":[
        "Reactive (WebFlux) security (@EnableWebFluxSecurity)",
        "ReactiveSecurityContextHolder",
        "ServerHttpSecurity DSL",
        "Reactive method security",
        "WebSocket security",
        "RSocket security",
        "CAS authentication",
        "Spring MVC integration (CurrentSecurityContextArgumentResolver)",
        "Jackson support (serializing security context)",
        "Localization of messages",
        "Observability (Micrometer) in security",
      ]},
    ]},
    {"name":"7. Testing","tag":"testing","groups":[
      {"g":"Test Support","items":[
        "spring-security-test dependency",
        "@WithMockUser",
        "@WithAnonymousUser",
        "@WithUserDetails",
        "@WithSecurityContext (custom)",
        "SecurityMockMvcRequestPostProcessors (user, csrf, httpBasic, etc.)",
        "SecurityMockMvcResultMatchers (authenticated, etc.)",
        "MockMvc form login / logout",
        "WebTestClient security (mutateWith)",
        "Testing OAuth2 (mockJwt, mockOpaqueToken, oauth2Login)",
        "Testing method security",
      ]},
    ]},
  ],
}

AUTHZ_SERVER = {
  "file":"spring-authorization-server.html","title":"Spring Authorization Server","logo":"A","cat":"Security",
  "subtitle":"A framework for building OAuth2 Authorization Server & OpenID Connect providers.",
  "sections":[
    {"name":"1. Overview & Getting Started","tag":"intro","groups":[
      {"g":"Foundations","items":[
        "What Spring Authorization Server is",
        "Relationship to Spring Security",
        "OAuth2.1 & OpenID Connect 1.0 conformance",
        "Replacing the deprecated Spring Security OAuth project",
        "Dependencies & minimum versions",
        "Default configuration & getting started",
        "Defining a SecurityFilterChain for the auth server",
        "OAuth2AuthorizationServerConfigurer",
        "Sample/Bootiful setup",
      ]},
    ]},
    {"name":"2. Core Components","tag":"core","groups":[
      {"g":"Registered Clients","items":[
        "RegisteredClient model",
        "RegisteredClientRepository (in-memory & JDBC)",
        "Client authentication methods (basic, post, JWT, none/PKCE)",
        "Client settings",
        "Redirect URIs & scopes",
        "Grant types per client",
      ]},
      {"g":"Authorization & Tokens","items":[
        "OAuth2Authorization model",
        "OAuth2AuthorizationService (in-memory & JDBC)",
        "OAuth2AuthorizationConsent & consent service",
        "Token generation (OAuth2TokenGenerator)",
        "JWT vs opaque access tokens",
        "JwtEncoder & JWK source",
        "OAuth2TokenCustomizer (custom claims)",
        "Refresh tokens",
        "Token settings (TTL, formats)",
        "Authorization server settings (issuer, endpoints)",
      ]},
    ]},
    {"name":"3. Protocol Endpoints","tag":"endpoints","groups":[
      {"g":"Endpoints & Flows","items":[
        "Authorization endpoint",
        "Token endpoint",
        "Token introspection endpoint",
        "Token revocation endpoint",
        "JWK Set endpoint",
        "OAuth2 authorization server metadata endpoint",
        "OIDC provider configuration endpoint",
        "OIDC UserInfo endpoint",
        "OIDC client registration endpoint",
        "OIDC logout endpoint",
        "Device authorization grant flow",
        "Device verification endpoint",
        "Authorization code grant with PKCE",
        "Client credentials grant",
        "Refresh token grant",
        "Token exchange grant",
      ]},
    ]},
    {"name":"4. Customization & Advanced","tag":"adv","groups":[
      {"g":"Customizing","items":[
        "Customizing form login / federated identity",
        "Custom consent page",
        "Custom claims & mappers",
        "Extending grant types",
        "Authentication providers customization",
        "JDBC persistence schemas",
        "Multi-tenancy",
        "Integration with social login as identity provider",
      ]},
    ]},
  ],
}

SESSION = {
  "file":"spring-session.html","title":"Spring Session","logo":"Se","cat":"Security",
  "subtitle":"Cluster-friendly HTTP session management decoupled from the container.",
  "sections":[
    {"name":"1. Overview & Core","tag":"core","groups":[
      {"g":"Concepts","items":[
        "Why Spring Session (clustered sessions, no container dependency)",
        "Session & SessionRepository abstractions",
        "FindByIndexNameSessionRepository",
        "SessionRepositoryFilter",
        "@EnableSpringHttpSession",
        "Replacing the HttpSession transparently",
        "Session expiration & cleanup",
        "Session events (created/deleted/expired)",
      ]},
      {"g":"Backends","items":[
        "Spring Session Data Redis (@EnableRedisHttpSession)",
        "Redis indexed session repository",
        "Redis (RedisIndexedSessionRepository vs RedisSessionRepository)",
        "Spring Session JDBC (@EnableJdbcHttpSession)",
        "Spring Session Hazelcast",
        "Spring Session MongoDB",
        "In-memory map session repository",
      ]},
    ]},
    {"name":"2. Web & WebSocket Integration","tag":"web","groups":[
      {"g":"Integration","items":[
        "HttpSessionStrategy (cookie vs header)",
        "CookieSerializer customization (SameSite, domain, path)",
        "Multiple sessions in one browser (session aliasing)",
        "WebSocket integration",
        "Spring Security concurrent session control with Spring Session",
        "Reactive (WebSession) support",
        "ReactiveSessionRepository",
        "REST API session via header",
        "Custom session attributes & serialization",
      ]},
    ]},
  ],
}

LDAP = {
  "file":"spring-ldap.html","title":"Spring LDAP","logo":"L","cat":"Security",
  "subtitle":"Java LDAP made simple — templating, object mapping, and transactions.",
  "sections":[
    {"name":"1. Core LDAP Support","tag":"core","groups":[
      {"g":"Templates & Operations","items":[
        "LdapTemplate overview",
        "ContextSource & LdapContextSource",
        "Connecting & pooling connections",
        "Searching (search, lookup)",
        "AttributesMapper",
        "ContextMapper",
        "Binding & unbinding entries",
        "Modifying attributes (ModificationItem)",
        "Building DNs (LdapNameBuilder / DistinguishedName)",
        "Filters (LdapQueryBuilder, hardcoded & encoded filters)",
        "LdapQuery API",
        "Paged & sorted searches",
        "Handling LDAP exceptions",
      ]},
    ]},
    {"name":"2. ODM, Transactions & Pooling","tag":"adv","groups":[
      {"g":"Advanced","items":[
        "Object-Directory Mapping (ODM) — @Entry, @Attribute, @Id, @DnAttribute",
        "ODM with LdapTemplate.findAll / find",
        "Spring Data LDAP repositories",
        "LDAP transactions (compensating transactions)",
        "ContextSource transaction manager",
        "Connection pooling (commons-pool2)",
        "Authentication (authenticate methods)",
        "Parsing LDIF files",
        "Embedded LDAP server (UnboundID) for testing",
        "Spring Boot LDAP auto-configuration",
      ]},
    ]},
  ],
}

PROJECTS = [SECURITY, AUTHZ_SERVER, SESSION, LDAP]
