# -*- coding: utf-8 -*-
"""Spring Batch, Modulith, Statemachine, Shell, Web Flow."""

BATCH = {
  "file":"spring-batch.html","title":"Spring Batch","logo":"Ba","cat":"Applications",
  "subtitle":"Robust batch processing — jobs, steps, chunk & tasklet processing, scaling.",
  "sections":[
    {"name":"1. Domain & Configuration","tag":"core","groups":[
      {"g":"Batch Domain Language","items":[
        "Batch processing concepts & use cases",
        "Job",
        "JobInstance",
        "JobParameters",
        "JobExecution",
        "Step",
        "StepExecution",
        "ExecutionContext",
        "JobRepository",
        "JobLauncher",
        "ItemReader / ItemProcessor / ItemWriter",
        "Batch architecture & layers",
      ]},
      {"g":"Configuring a Job","items":[
        "Java configuration (@EnableBatchProcessing / modular)",
        "JobBuilder & StepBuilder",
        "Configuring a JobRepository",
        "In-memory vs persistent JobRepository",
        "Configuring a JobLauncher",
        "Running a job (from CLI, web, scheduler)",
        "Spring Boot batch auto-config & JobLauncherApplicationRunner",
        "JobParametersIncrementer",
        "JobParametersValidator",
        "Job listeners (JobExecutionListener)",
        "Restartability",
        "Preventing restart / restart limits",
        "Running jobs from the command line (CommandLineJobRunner)",
        "Stopping a job",
        "Aborting a job",
        "Metadata schema & DDL",
      ]},
    ]},
    {"name":"2. Step Processing","tag":"step","groups":[
      {"g":"Chunk-oriented Processing","items":[
        "Chunk-oriented processing model",
        "Commit interval / chunk size",
        "Configuring a Step (chunk)",
        "ItemReader interface & usage",
        "ItemWriter interface & usage",
        "ItemProcessor interface & usage",
        "Filtering records (returning null)",
        "Chaining ItemProcessors (CompositeItemProcessor)",
        "ItemStream (open/update/close)",
        "Fault tolerance",
        "Skip logic (skip, skipLimit, skip policy)",
        "Retry logic (retry, retryLimit, retry policy)",
        "Controlling rollback (no-rollback exceptions)",
        "Transaction attributes per step",
        "Restart & ExecutionContext for restart",
        "Registering ItemStreams",
        "Intercepting step execution (listeners: step/chunk/item/read/write/process/skip)",
      ]},
      {"g":"Tasklet & Flow","items":[
        "TaskletStep",
        "Custom Tasklet implementation",
        "TaskletStep chunk vs tasklet",
        "Controlling step flow (transitions on exit status)",
        "Conditional flow & FlowBuilder",
        "Programmatic flow decisions (JobExecutionDecider)",
        "Split flows (parallel)",
        "Externalizing flow definitions",
        "Sequential vs conditional flow",
        "Ending a job (end/fail/stop)",
        "ExitStatus & BatchStatus",
      ]},
    ]},
    {"name":"3. Readers, Writers & Processors","tag":"io","groups":[
      {"g":"Built-in I/O","items":[
        "Flat file ItemReader (FlatFileItemReader)",
        "LineMapper / FieldSetMapper / LineTokenizer",
        "Fixed-length & delimited files",
        "Multi-line records",
        "FlatFileItemWriter",
        "XML I/O (StaxEventItemReader/Writer)",
        "JSON I/O (JsonItemReader/Writer)",
        "Database readers (JdbcCursorItemReader, JdbcPagingItemReader)",
        "JPA readers (JpaCursorItemReader, JpaPagingItemReader)",
        "Hibernate readers",
        "Database writers (JdbcBatchItemWriter, JpaItemWriter)",
        "Stored procedure reader",
        "MongoDB / Neo4j / other item readers & writers",
        "Kafka item reader/writer",
        "Reading & writing in multiple files (MultiResourceItemReader/Writer)",
        "Composite & classifier writers",
        "Reusing existing services (ItemReaderAdapter, ItemWriterAdapter)",
        "Validating input (ValidatingItemProcessor / BeanValidatingItemProcessor)",
        "Preventing state persistence (saveState=false)",
        "Creating custom ItemReaders/Writers",
      ]},
    ]},
    {"name":"4. Scaling & Advanced","tag":"adv","groups":[
      {"g":"Scaling","items":[
        "Multi-threaded step",
        "Parallel steps",
        "Remote chunking",
        "Partitioning (Partitioner / PartitionHandler)",
        "Local partitioning (TaskExecutorPartitionHandler)",
        "Remote partitioning",
        "StepExecutionAggregator",
      ]},
      {"g":"Advanced & Integration","items":[
        "Late binding of job/step attributes (@StepScope / @JobScope)",
        "Listeners & ExecutionContext promotion (ExecutionContextPromotionListener)",
        "Common batch patterns",
        "Logging item processing & failures",
        "Stopping/restarting gracefully",
        "Handling reader/writer errors",
        "Spring Batch + Spring Integration (job launching, informational messages)",
        "Spring Cloud Task / Data Flow integration",
        "Testing batch jobs (JobLauncherTestUtils, JobRepositoryTestUtils)",
        "@SpringBatchTest",
        "Testing step-scoped components",
        "Observability (Micrometer metrics & tracing)",
        "Batch processing & JSR-352 (javax/jakarta batch)",
      ]},
    ]},
  ],
}

MODULITH = {
  "file":"spring-modulith.html","title":"Spring Modulith","logo":"M","cat":"Applications",
  "subtitle":"Build well-structured, modular monoliths and verify their boundaries.",
  "sections":[
    {"name":"1. Modules & Verification","tag":"core","groups":[
      {"g":"Application Modules","items":[
        "Modular monolith concept",
        "Application modules model",
        "ApplicationModules (creating the model)",
        "Module detection (by package / by annotation)",
        "Allowed dependencies & explicit dependencies",
        "Named interfaces (@NamedInterface)",
        "Open vs closed modules (@ApplicationModule)",
        "Hiding internals (package visibility)",
        "Verifying modular structure (verify())",
        "Excluding packages",
        "Customizing module detection (ApplicationModuleDetectionStrategy)",
      ]},
      {"g":"Documentation","items":[
        "Generating documentation (Documenter)",
        "Component diagrams (C4 / UML via Structurizr)",
        "Module canvas",
        "PlantUML output",
        "Documenting application module relations",
      ]},
    ]},
    {"name":"2. Events, Testing & Observability","tag":"adv","groups":[
      {"g":"Events","items":[
        "Working with application events",
        "Event publication registry (transactional outbox)",
        "@ApplicationModuleListener",
        "Event externalization (Kafka, AMQP, JMS, SQS)",
        "Completing & republishing failed events",
        "Persistence (JPA / JDBC / MongoDB) for event publications",
      ]},
      {"g":"Testing & Runtime","items":[
        "Integration testing modules (@ApplicationModuleTest)",
        "Bootstrap modes (standalone, direct dependencies, all dependencies)",
        "Scenario API for event-based tests",
        "Test execution & module isolation",
        "Observability (per-module tracing/metrics)",
        "Runtime support (ApplicationModulesRuntime)",
        "Actuator endpoint for modules",
        "Spring Boot integration & moments (time-based events)",
      ]},
    ]},
  ],
}

STATEMACHINE = {
  "file":"spring-statemachine.html","title":"Spring Statemachine","logo":"Sm","cat":"Applications",
  "subtitle":"A framework for application developers to use state machine concepts.",
  "sections":[
    {"name":"1. Core State Machine","tag":"core","groups":[
      {"g":"Concepts & Config","items":[
        "State machine concepts (states, events, transitions, actions, guards)",
        "Finite state machine theory & terms",
        "StateMachine interface",
        "@EnableStateMachine / @EnableStateMachineFactory",
        "Configuring states (StateConfigurer)",
        "Initial & end states",
        "Configuring transitions (external, internal, local)",
        "Events & triggering (sendEvent)",
        "Actions (entry/exit/state/transition)",
        "Guards (guard conditions)",
        "StateMachine configuration (config builders)",
        "Hierarchical (sub) states",
        "Regions & orthogonal states",
        "Pseudo states (choice, junction, fork, join, history, entry/exit point)",
        "Triggers (event-based, timer-based)",
        "Deferred events",
      ]},
    ]},
    {"name":"2. Advanced & Integration","tag":"adv","groups":[
      {"g":"Context & Persistence","items":[
        "Extended state (variables)",
        "StateContext",
        "StateMachine listeners (StateMachineListener)",
        "StateMachineInterceptor",
        "Persisting state machine (StateMachinePersister)",
        "Persistence backends (JPA, Redis, MongoDB)",
        "StateMachineRuntimePersister",
        "State machine factory & multiple instances",
        "Spring Security integration (securing transitions)",
        "Distributed state machine (Zookeeper, leader election)",
        "Error handling",
        "Event result & reactive API (Mono/Flux)",
        "Monitoring (StateMachineMonitor)",
        "Testing (StateMachineTestPlan)",
        "UML / Eclipse Papyrus modeling support",
        "State machine DSL & factories from UML",
      ]},
    ]},
  ],
}

SHELL = {
  "file":"spring-shell.html","title":"Spring Shell","logo":"Sh","cat":"Applications",
  "subtitle":"Build interactive command-line (REPL) applications with Spring.",
  "sections":[
    {"name":"1. Commands & I/O","tag":"core","groups":[
      {"g":"Defining Commands","items":[
        "Interactive shell / REPL concept",
        "@ShellComponent & @ShellMethod",
        "@ShellOption (named options, defaults, arity)",
        "Command registration (programmatic / annotation)",
        "Command availability (@ShellMethodAvailability)",
        "Command groups",
        "Built-in commands (help, clear, exit, history, script, etc.)",
        "Command catalog",
        "Dynamic command registration",
        "New annotation model (@Command / @Option / command-class)",
      ]},
      {"g":"Input, Output & Styling","items":[
        "Type conversion of parameters",
        "Custom converters",
        "Validation of input",
        "Interactive vs non-interactive (script) mode",
        "Prompt customization (PromptProvider)",
        "Output styling (JLine, ANSI, AttributedString)",
        "Tables rendering (TableBuilder)",
        "Progress & spinner UI",
        "Theming & ThemeResolver",
      ]},
    ]},
    {"name":"2. Interactivity & Advanced","tag":"adv","groups":[
      {"g":"Advanced Features","items":[
        "TAB completion (CompletionProvider / ValueProvider)",
        "Command history",
        "Line reader customization (JLine)",
        "Flow / interactive components (single select, multi select, confirmation, path input, string input)",
        "Component context & rendering",
        "Error handling & exception resolvers",
        "Exit code mapping",
        "Custom error handling",
        "Terminal & ANSI handling",
        "Spring Boot integration & auto-config",
        "Testing shell commands (ShellTestClient)",
        "Non-interactive command-line invocation",
      ]},
    ]},
  ],
}

WEBFLOW = {
  "file":"spring-web-flow.html","title":"Spring Web Flow","logo":"Wf","cat":"Applications",
  "subtitle":"Implement controlled navigation/flows in web applications.",
  "sections":[
    {"name":"1. Defining Flows","tag":"core","groups":[
      {"g":"Flow Definition","items":[
        "Web flow concept (guided navigation / wizards)",
        "Flow definition language (XML)",
        "States: view-state",
        "States: action-state",
        "States: decision-state",
        "States: subflow-state",
        "States: end-state",
        "Transitions & events",
        "Flow variables (var)",
        "Flow input & output mapping",
        "Scopes (request, flash, view, flow, conversation)",
        "Actions (evaluate, set, render)",
        "Expression language (EL / SpEL) in flows",
        "Checkpointing & flow execution",
      ]},
    ]},
    {"name":"2. Integration & Features","tag":"adv","groups":[
      {"g":"Integration","items":[
        "Spring MVC integration (FlowHandlerMapping / FlowHandlerAdapter)",
        "FlowExecutor & flow execution repository",
        "JSF integration",
        "Securing flows (Spring Security)",
        "Flow inheritance",
        "Flow managed persistence context (JPA/Hibernate)",
        "Partial rendering & Ajax (Spring JS)",
        "Validation in view states",
        "Model binding & data binding",
        "Subflows & flow composition",
        "Custom state & transition behavior",
        "Testing flows (AbstractXmlFlowExecutionTests)",
      ]},
    ]},
  ],
}

PROJECTS = [BATCH, MODULITH, STATEMACHINE, SHELL, WEBFLOW]
